### ISSUE TITLE
exaile tries to load a music database even though it does not exist

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#100]
Steps to reproduce:
run exaile with the `--all-data-dir=/some/empty/directory` option. After "INFO    : Loading collection..." is printed it will give this error three times:

```
ERROR   : Exception occurred while loading /tmp/test1/music.db
Traceback (most recent call last):
  File "/path/to/exaile/xl/trax/trackdb.py", line 226, in load_from_location
    setattr(self, attr, pdata[attr])
  File "/usr/lib64/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: '_serial_libraries'
```

This bug is present in both gi branch (with backtrace above) and master. In master it just prints
```
WARNING : Exception occurred while loading /tmp/mstdr/music.db
```

This is not fatal in both cases.

**Comment by genodeftest** [comment]
The full error message from current gi:
~~~
ERROR   : Exception occurred while loading /tmp/nduaroa/music.db
Traceback (most recent call last):
  File "/home/christian/.local/src/exaile/exaile/xl/trax/trackdb.py", line 226, in load_from_location
    setattr(self, attr, pdata[attr])
  File "/usr/lib64/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: '_serial_libraries'
ERROR   : Exception occurred while loading /tmp/nduaroa/music.db
Traceback (most recent call last):
  File "/home/christian/.local/src/exaile/exaile/xl/trax/trackdb.py", line 226, in load_from_location
    setattr(self, attr, pdata[attr])
  File "/usr/lib64/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: 'name'
ERROR   : Exception occurred while loading /tmp/nduaroa/music.db
Traceback (most recent call last):
  File "/home/christian/.local/src/exaile/exaile/xl/trax/trackdb.py", line 226, in load_from_location
    setattr(self, attr, pdata[attr])
  File "/usr/lib64/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
KeyError: '_key'
~~~

**Comment by virtuald** [comment]
Fixed.

**Comment by genodeftest** [comment]
Confirmed. Thank you!
