### ISSUE TITLE
Unable to enable plugin gnomemmkeys : Method "GrabMediaPlayerKeys" with signature "si" on interface "org.mate.SettingsDaemon.MediaKeys" doesn't exist

### ISSUE THREAD

**Issue by Gwend4l** [exaile/exaile#122]
Hi!

Using Fedora 22, I have the following exaile 3.4.3 issue since yesterday: I can't enable the plugin gnomemmkeys (GNOME Multimedia Keys) anymore. It gives me the following error:
~~~~~~~~
Traceback (most recent call last):
  File "/usr/share/exaile/xl/plugins.py", line 148, in enable_plugin
    plugin.enable(self.exaile)
  File "/usr/share/exaile/plugins/gnomemmkeys/__init__.py", line 52, in enable
    _enable(None, player.PLAYER, None)
  File "/usr/share/exaile/plugins/gnomemmkeys/__init__.py", line 90, in _enable
    GNOME_MMKEYS.GrabMediaPlayerKeys("Exaile", 0)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "GrabMediaPlayerKeys" with signature "si" on interface "org.mate.SettingsDaemon.MediaKeys" doesn't exist

WARNING : Unable to enable plugin gnomemmkeys
~~~~~~~~

I hava no idea why this is happening, since there was no exaile update in the previous days. Here is a list of all the fedora packages I've installed/updated yesterday, if that might help:
~~~~~~~~
  libICE-devel-1.0.9-2.fc22.x86_64      @fedora
  libSM-devel-1.2.2-2.fc22.x86_64       @fedora
  libXt-devel-1.1.4-10.fc22.x86_64      @fedora
  libXv-devel-1.0.10-2.fc22.x86_64      @fedora
  mesa-libGLU-devel-9.0.0-7.fc22.x86_64 @fedora
  qt-devel-1:4.8.6-30.fc22.x86_64       @fedora

 autoconf-2.69-18.fc22.noarch                        @fedora
          2.69-20.fc22.noarch                        @updates
 bash-4.3.39-1.fc22.x86_64                           @updates
      4.3.39-3.fc22.x86_64                           @updates
 breeze-icon-theme-5.3.1-1.fc22.noarch               @updates
                   5.3.2-1.fc22.noarch               @updates
 caja-schemas-1.10.1-2.fc22.x86_64                   @updates
              1.10.1-3.fc22.x86_64                   @updates
 file-roller-3.16.2-1.fc22.x86_64                    @updates-testing
             3.16.3-1.fc22.x86_64                    @updates
 file-roller-nautilus-3.16.2-1.fc22.x86_64           @updates-testing
                      3.16.3-1.fc22.x86_64           @updates
  libmatemixer-1.10.0-2.fc22.x86_64                   @updates
 libwsman1-2.4.12-1.fc22.x86_64                      (unknown)
           2.4.15-1.fc22.x86_64                      @updates
 mate-control-center-1.10.0-1.fc22.x86_64            @updates-testing
                     1.10.0-2.fc22.x86_64            @updates
 mate-control-center-filesystem-1.10.0-1.fc22.x86_64 @updates-testing
                                1.10.0-2.fc22.x86_64 @updates
  mate-settings-daemon-1.10.0-1.fc22.x86_64           @fedora
 openjpeg2-2.1.0-3.fc22.x86_64                       (unknown)
           2.1.0-5.fc22.x86_64                       @updates
 perl-threads-1:2.01-1.fc22.x86_64                   (unknown)
              1:2.02-1.fc22.x86_64                   @updates
 policycoreutils-2.3-16.fc22.x86_64                  (unknown)
                 2.3-17.fc22.x86_64                  @updates
 policycoreutils-python-2.3-16.fc22.x86_64           (unknown)
                        2.3-17.fc22.x86_64           @updates
 stunnel-5.16-1.fc22.x86_64                          @updates
         5.17-1.fc22.x86_64                          @updates
 tigervnc-1.4.3-7.fc22.x86_64                        @updates
          1.4.3-8.fc22.x86_64                        @updates
 tigervnc-icons-1.4.3-7.fc22.noarch                  @updates
                1.4.3-8.fc22.noarch                  @updates
 tigervnc-license-1.4.3-7.fc22.noarch                @updates
                  1.4.3-8.fc22.noarch                @updates
 tigervnc-server-1.4.3-7.fc22.x86_64                 @updates
                 1.4.3-8.fc22.x86_64                 @updates
 tigervnc-server-minimal-1.4.3-7.fc22.x86_64         @updates
                         1.4.3-8.fc22.x86_64         @updates
 wine-1.7.45-1.fc22.x86_64                           @updates
      1.7.46-1.fc22.x86_64                           @updates
 wine-alsa-1.7.45-1.fc22.x86_64                      @updates
  wine-alsa-1.7.46-1.fc22.i686                        @updates
 wine-alsa-1.7.46-1.fc22.x86_64                      @updates
 wine-arial-fonts-1.7.45-1.fc22.noarch               @updates
                  1.7.46-1.fc22.noarch               @updates
 wine-capi-1.7.45-1.fc22.i686                        @updates
 wine-capi-1.7.45-1.fc22.x86_64                      @updates
           1.7.46-1.fc22.i686                        @updates
           1.7.46-1.fc22.x86_64                      @updates
 wine-cms-1.7.45-1.fc22.i686                         @updates
 wine-cms-1.7.45-1.fc22.x86_64                       @updates
          1.7.46-1.fc22.i686                         @updates
          1.7.46-1.fc22.x86_64                       @updates
 wine-common-1.7.45-1.fc22.noarch                    @updates
             1.7.46-1.fc22.noarch                    @updates
 wine-core-1.7.45-1.fc22.i686                        @updates
 wine-core-1.7.45-1.fc22.x86_64                      @updates
           1.7.46-1.fc22.i686                        @updates
           1.7.46-1.fc22.x86_64                      @updates
 wine-courier-fonts-1.7.45-1.fc22.noarch             @updates
                    1.7.46-1.fc22.noarch             @updates
 wine-desktop-1.7.45-1.fc22.noarch                   @updates
              1.7.46-1.fc22.noarch                   @updates
 wine-filesystem-1.7.45-1.fc22.noarch                @updates
                 1.7.46-1.fc22.noarch                @updates
 wine-fixedsys-fonts-1.7.45-1.fc22.noarch            @updates
                     1.7.46-1.fc22.noarch            @updates
 wine-fonts-1.7.45-1.fc22.noarch                     @updates
            1.7.46-1.fc22.noarch                     @updates
 wine-ldap-1.7.45-1.fc22.i686                        @updates
 wine-ldap-1.7.45-1.fc22.x86_64                      @updates
           1.7.46-1.fc22.i686                        @updates
           1.7.46-1.fc22.x86_64                      @updates
 wine-marlett-fonts-1.7.45-1.fc22.noarch             @updates
                    1.7.46-1.fc22.noarch             @updates
 wine-ms-sans-serif-fonts-1.7.45-1.fc22.noarch       @updates
                          1.7.46-1.fc22.noarch       @updates
 wine-openal-1.7.45-1.fc22.i686                      @updates
 wine-openal-1.7.45-1.fc22.x86_64                    @updates
             1.7.46-1.fc22.i686                      @updates
             1.7.46-1.fc22.x86_64                    @updates
 wine-opencl-1.7.45-1.fc22.i686                      @updates
 wine-opencl-1.7.45-1.fc22.x86_64                    @updates
             1.7.46-1.fc22.i686                      @updates
             1.7.46-1.fc22.x86_64                    @updates
 wine-pulseaudio-1.7.45-1.fc22.i686                  @updates
 wine-pulseaudio-1.7.45-1.fc22.x86_64                @updates
                 1.7.46-1.fc22.i686                  @updates
                 1.7.46-1.fc22.x86_64                @updates
 wine-small-fonts-1.7.45-1.fc22.noarch               @updates
                  1.7.46-1.fc22.noarch               @updates
 wine-symbol-fonts-1.7.45-1.fc22.noarch              @updates
                   1.7.46-1.fc22.noarch              @updates
 wine-system-fonts-1.7.45-1.fc22.noarch              @updates
                   1.7.46-1.fc22.noarch              @updates
 wine-systemd-1.7.45-1.fc22.noarch                   @updates
              1.7.46-1.fc22.noarch                   @updates
 wine-tahoma-fonts-1.7.45-1.fc22.noarch              @updates
                   1.7.46-1.fc22.noarch              @updates
 wine-twain-1.7.45-1.fc22.i686                       @updates
 wine-twain-1.7.45-1.fc22.x86_64                     @updates
            1.7.46-1.fc22.i686                       @updates
            1.7.46-1.fc22.x86_64                     @updates
 wine-wingdings-fonts-1.7.45-1.fc22.noarch           @updates
                      1.7.46-1.fc22.noarch           @updates
 wxBase3-3.0.2-5.fc22.x86_64                         @updates
         3.0.2-8.fc22.x86_64                         @updates
 wxGTK3-3.0.2-5.fc22.x86_64                          @updates
        3.0.2-8.fc22.x86_64                          @updates
 wxGTK3-gl-3.0.2-5.fc22.x86_64                       @updates
           3.0.2-8.fc22.x86_64                       @updates
 wxGTK3-media-3.0.2-5.fc22.x86_64                    @updates
              3.0.2-8.fc22.x86_64                    @updates
 xen-libs-4.5.0-11.fc22.x86_64                       @updates
          4.5.1-1.fc22.x86_64                        @updates
 xen-licenses-4.5.0-11.fc22.x86_64                   @updates
              4.5.1-1.fc22.x86_64                    @updates
 youtube-dl-2015.06.04.1-2.fc22.noarch               @updates
            2015.07.04-1.fc22.noarch                 @updates
~~~~~~~~

I can provide more information if required.

also, thanks for Exaile! :)

**Comment by genodeftest** [comment]
caja-schemas, mate-control-center and mate-settings-daemon should be related, probably the last one. Can you try a `dnf downgrade mate-settings-daemon`?

**Comment by Gwend4l** [comment]
After a quick look at dnf history, it seems that `mate-settings-daemon` was installed as a new dependency of an updated package. Hence:
~~~~~
$ sudo dnf downgrade mate-settings-daemon
Last metadata expiration check performed 1:50:22 ago on Tue Jul  7 08:41:10 2015.
Package mate-settings-daemon of lowest version already installed, cannot downgrade it.
Error: Nothing to do.
~~~~~

So I've uninstalled it, since I'm using GNOME right now and I don't need MATE anymore. And after a reboot it worked! Thanks! :)

**Comment by genodeftest** [comment]
So it looks like either gnomemmkeys plugin is unable to use the correct dbus interface or mate-settings-daemon is broken.

**Comment by sjohannes** [comment]
I checked MATE's D-Bus service a while ago, and if I remember correctly, the version of MATE I used also responds on the GNOME busname/object/interface so it *should* work. Feel free to reopen if this is still an issue.
