### ISSUE TITLE
Reading metadata from wav files fails

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#143]
Quite often when reading metadata from wav files e.g. by (re-)scanning a music collection, I get this error:
~~~
ERROR   : Error reading tags for file:///path/to/track01.wav
Traceback (most recent call last):
  File "/path/to/exaile/xl/trax/track.py", line 347, in read_tags
    f = metadata.get_format(loc)
  File "/path/to/exaile/xl/metadata/__init__.py", line 122, in get_format
    return formatclass(loc)
  File "/path/to/exaile/xl/metadata/_base.py", line 78, in __init__
    self.load()
  File "/path/to/exaile/xl/metadata/wav.py", line 50, in load
    ext = os.path.splitext(loc)[1][1:].lower()
  File "/usr/lib64/python2.7/posixpath.py", line 98, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)
  File "/usr/lib64/python2.7/genericpath.py", line 99, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'
~~~

**Comment by virtuald** [comment]
Interesting. It would be great if you could generate a sample file with the problem and add it to https://github.com/exaile/exaile-test-files

**Comment by virtuald** [comment]
Sorry for the delay, totally forgot about this.
