### ISSUE TITLE
[gi branch] TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#193]
I sometimes get these tracebacks when playing files from a playlist:
```
Traceback (most recent call last):
  File "/path/to/exaile/xlgui/widgets/playlist.py", line 943, in scroll_to_current
    self.scroll_to_cell(path)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py", line 1293, in scroll_to_cell
    path = TreePath(path)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py", line 1146, in __new__
    path = ":".join(str(val) for val in path)
TypeError: 'NoneType' object is not iterable
```
I am running current (4.0 gi branch) exaile from git.

**Comment by virtuald** [comment]
Hm, you really shouldn't, but oh well..

**Comment by genodeftest** [comment]
This might be a result of #192.
