### ISSUE TITLE
The 'Properties' dialog doesn't show up when the ID3 tag has a string in the BPM field (Exaile 3.4.5)

### ISSUE THREAD

**Issue by strahlc** [exaile/exaile#209]
If a mp3 File has a string value (like 'abc') in the ID3 BPM field, the properties dialog cannot be opened.

**Comment by strahlc** [comment]
Traceback (most recent call last):
  File "/usr/lib64/exaile/xlgui/widgets/playlist.py", line 350, in <lambda>
    gtk.STOCK_PROPERTIES, lambda w, n, o, c: o.show_properties_dialog()))
  File "/usr/lib64/exaile/xlgui/widgets/playlist.py", line 1178, in show_properties_dialog
    current_position, with_extras)
  File "/usr/lib64/exaile/xlgui/properties.py", line 128, in __init__
    self._build_from_track(self.current_position)
  File "/usr/lib64/exaile/xlgui/properties.py", line 321, in _build_from_track
    self.rows.append(TagRow(self, self.tags_table, field, tag, entry, i))
  File "/usr/lib64/exaile/xlgui/properties.py", line 575, in __init__
    self.field.set_value(value, all_vals)
  File "/usr/lib64/exaile/xlgui/properties.py", line 754, in set_value
    self.field.set_value(float(val))
ValueError: could not convert string to float: abc

**Comment by strahlc** [comment]
Unfortunately, I have some files with bad ID3 tags.

Exaile shows the following warnings on the console:
```
/usr/lib64/exaile/xl/main.py:327: Warning: unable to set property 'rating' of type 'gint' from value of type 'gchararray'
  self.gui.main.window.show_all()
INFO    : WARNING: could not open podcast file
INFO    : Playing file:///home/username/music/filename.mp3
/usr/lib64/exaile/xlgui/__init__.py:77: Warning: unable to set property 'rating' of type 'gint' from value of type 'gchararray'
  gtk.main()
```

**Comment by virtuald** [comment]
I think those warnings happen regardless of the file, it's fixed in the current master.

**Comment by strahlc** [comment]
In this file is the BPM value set correctly, but an other value (expected number) seems to contain a string.
```
Traceback (most recent call last):
  File "/usr/lib64/exaile/xlgui/widgets/playlist.py", line 350, in <lambda>
    gtk.STOCK_PROPERTIES, lambda w, n, o, c: o.show_properties_dialog()))
  File "/usr/lib64/exaile/xlgui/widgets/playlist.py", line 1178, in show_properties_dialog
    current_position, with_extras)
  File "/usr/lib64/exaile/xlgui/properties.py", line 128, in __init__
    self._build_from_track(self.current_position)
  File "/usr/lib64/exaile/xlgui/properties.py", line 295, in _build_from_track
    row = TagRow(self, self.tags_table, field, tag, entry, i)
  File "/usr/lib64/exaile/xlgui/properties.py", line 575, in __init__
    self.field.set_value(value, all_vals)
  File "/usr/lib64/exaile/xlgui/properties.py", line 829, in set_value
    self.field[x].set_value(float(vals[x]))
ValueError: could not convert string to float: example.com
```
