### ISSUE TITLE
[gnomemmkeys] Plugin should fail more gracefully if it cannot be enabled

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#219]
Steps to reproduce:
1. start exaile in a Gnome session
2. enable plugin gnomemmkeys
3. quit exaile
4. switch to KDE plasma session
5. start exaile

You'll get this traceback:

```
Traceback (most recent call last):                                                                     
  File "/path/to/exaileplugins/gnomemmkeys/__init__.py", line 78, in _enable                                                                                                      
    '/org/gnome/SettingsDaemon')                                                                       
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon was not provided by any .service files
```

Instead I think you should see a message on cli that this plugin failed and disable the plugin.

**Comment by genodeftest** [comment]
For fixing this issue, #103 should be fixed previously.

**Comment by genodeftest** [comment]
Closing, because the plugin gnomemmkeys has been removed in eb222c1088d9d47e05729848150c97fa3fd99d07 and #293
