### ISSUE TITLE
Another encoding-related traceback

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#229]
I just got this when starting Exaile 4.0.0dev+a820c4e:

```
Traceback (most recent call last):
  File "/path/to/exaile/xl/main.py", line 330, in __init__
    self.__init()
  File "/path/to/exaile/xl/main.py", line 504, in __init
    self.gui = xlgui.Main(self)
  File "/path/to/exaile/xlgui/__init__.py", line 124, in __init__
    self.main = main.MainWindow(self, self.builder, exaile.collection)
  File "/path/to/exaile/xlgui/main.py", line 137, in __init__
    self._setup_widgets()
  File "/path/to/exaile/xlgui/main.py", line 231, in _setup_widgets
    self.playlist_container = PlaylistContainer('saved_tabs', player.PLAYER)
  File "/path/to/exaile/xlgui/playlist_container.py", line 499, in __init__
    self.notebooks.append(PlaylistNotebook(manager_name, player, '<Control><Shift>t'))
  File "/path/to/exaile/xlgui/playlist_container.py", line 119, in __init__
    self.tab_manager = PlaylistManager(manager_name)
  File "/path/to/exaile/xl/playlist.py", line 1963, in __init__
    self.load_names()
  File "/path/to/exaile/xl/playlist.py", line 2031, in load_names
    pl.load_from_location(os.path.join(self.playlist_dir, f))
  File "/path/to/exaile/xl/playlist.py", line 1466, in load_from_location
    track = trax.Track(uri=loc)
  File "/path/to/exaile/xl/trax/track.py", line 229, in __init__
    self.set_loc(uri)
  File "/path/to/exaile/xl/trax/track.py", line 262, in set_loc
    event.log_event('track_tags_changed', self, '__loc')
  File "/path/to/exaile/xl/event.py", line 77, in log_event
    EVENT_MANAGER.emit(e)
  File "/path/to/exaile/xl/event.py", line 287, in emit
    self._emit(event, self.all_callbacks, emit_logmsg, emit_verbose)
  File "/path/to/exaile/xl/event.py", line 354, in _emit
    {'type' : event.type, 'object' : repr(event.object),
  File "/path/to/exaile/xl/trax/track.py", line 416, in __repr__
    return str(self)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 33: ordinal not in range(128)
```

**Comment by genodeftest** [comment]
Shorter traceback, same position. This happens when scanning my collection into a fresh exaile profile:
```
raceback (most recent call last):
  File "/path/to/exaile/xl/event.py", line 305, in _emit_pending
    self._emit(*event)
  File "/path/to/exaile/xl/event.py", line 354, in _emit
    {'type' : event.type, 'object' : repr(event.object),
  File "/path/to/exaile/xl/trax/track.py", line 416, in __repr__
    return str(self)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u011f' in position 16: ordinal not in range(128)
```
