### ISSUE TITLE
TypeError when trying to enable plugin inhibitsuspend

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#26]
When trying to enable the plugin “inhibitsuspend“ I get this warning logged to stdout:
~~~
Traceback (most recent call last):
  File "/path/to/exaile/xl/plugins.py", line 148, in enable_plugin
    plugin.enable(self.exaile)
  File "/path/to/exaile/plugins/inhibitsuspend/__init__.py", line 32, in enable
    SUSPEND_PLUGIN = SuspendInhibit()
  File "/path/to/exaile/plugins/inhibitsuspend/__init__.py", line 66, in __init__
    self.adapter = GnomeAdapter()
  File "/path/to/exaile/plugins/inhibitsuspend/__init__.py", line 233, in __init__
    'org.gnome.SessionManager')
  File "/path/to/exaile/plugins/inhibitsuspend/__init__.py", line 114, in __init__
    adapters.PlaybackAdapter.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)
WARNING : Unable to enable plugin inhibitsuspend
~~~
This happens on a Gnome 3.14 environment.

I see two possible fixes:
1. In xl/player/adapters.py remove necessity to give the player as an argument. Its use in adapters.py could be replaced by PLAYER from xl/player as done in the inhibitsuspend init:
~~~
from xl.player import PLAYER
~~~
This will have side-effects on plugins/minimode/controls.py and plugins/osd/__init_py .

2. In plugins/inhibitsuspend/__init__.py change line 114 from
~~~
adapters.PlaybackAdapter.__init__(self)
~~~
to
~~~
adapters.PlaybackAdapter.__init__(self, PLAYER)
~~~
This does not have any side-effects. It tried it and it works fine.

I don't know which one you'll prefer.

**Comment by virtuald** [comment]
Thanks!
