### ISSUE TITLE
Type errors affecting moodbar and lyrics

### ISSUE THREAD

**Issue by tfree87** [exaile/exaile#262]
After cloning the most recent version of Exaile today and running `exaile.py` from using Python 2.7.11. I noticed that sometimes I get an assertion error because the uri passed to the `_get_cache_path()` function of /.../exaile/plugins/moodbar/cache.py is sometimes of type **unicode** string instead of type **bytes**.

```text
ERROR   : Event callback exception caught!
Traceback (most recent call last):
  File "/.../exaile/xl/event.py", line 345, in _emit
    event.data, *cb.args, **cb.kwargs)
  File "/.../exaile/plugins/moodbar/__init__.py", line 128, in _on_playback_track_start
    data = cache.get(uri) if cache else None
  File "/.../exaile/plugins/moodbar/cache.py", line 56, in get
    with open(self._get_cache_path(uri), 'rb') as f:
  File "/.../exaile/plugins/moodbar/cache.py", line 72, in _get_cache_path
    assert isinstance(uri, bytes)
AssertionError
```

If I change the following line in `_get_cache_path()`:

```python
assert isinstance(uri, bytes)
```

to:

```python
if not isinstance(uri, bytes):
    uri = bytes(uri)
```

then the issue appears to be fixed and the moodbar loads for all of my files. Has anyone else had this issue? Some tracks seem to have a uri that is of type **string** while others are of type **unicode**.

For each track that leads to this assertion error there is also an error from `lyrics.py`:

```text
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/.../exaile/plugins/lyricsviewer/__init__.py", line 258, in get_lyrics
    lyrics_found = lyrics.MANAGER.find_all_lyrics(track, refresh)
  File "/.../exaile/xl/lyrics.py", line 215, in find_all_lyrics
    (lyrics, source, url) = self._find_cached_lyrics(method, track, refresh)
  File "/.../exaile/xl/lyrics.py", line 253, in _find_cached_lyrics
    if key in self.cache:
  File "/.../github/exaile/xl/lyrics.py", line 98, in __contains__
    return key in self.db
  File "/usr/lib64/python2.7/shelve.py", line 110, in __contains__
    return key in self.dict
  File "/usr/lib64/python2.7/_abcoll.py", line 388, in __contains__
    self[key]
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
TypeError: String or Integer object expected for key, unicode found
```

This can be solved similarly to the solution above but it seems that it would be better to fix these issues elsewhere in the code by ensuring that every uri in the playlist is an instance of the same type.

It seems that sometimes the returned `key` from `__contains__()` in `lyrics.py` is sometimes of type **unicode** or type **string**.

**Comment by tfree87** [comment]
I think I may have a fix. Ensuring that all file locations returned from `get_loc_for_io()` in `track.py` are of type `str` has silenced these issues.

This commit shows the change: 5e585f1

**Comment by sjohannes** [comment]
I'm confused how you end up with a unicode `__loc` in the first place.

```py
    def set_loc(self, loc):
        """
            Sets the location.
            :param loc: the location, as either a uri or a file path.
        """
        self.__unregister()
        gloc = Gio.File.new_for_commandline_arg(loc)
        self.__tags['__loc'] = gloc.get_uri()
        self.__register()
        event.log_event('track_tags_changed', self, '__loc')
```

`gloc.get_uri()` always returns str/bytes. Unless there's buggy code that sets `__loc` directly (which shows a warning).

Did you previously run Exaile under Python 3, perhaps? There `get_uri` returns str/unicode.

**Comment by tfree87** [comment]
I must have first created my collection when I was testing the program in Python 3. After removing all cache and configuration files and reloading the entire collection, there is now no longer any issue.
