### ISSUE TITLE
moodbar: Filename length limit too easily reached on files with Unicode names

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#297]
When you have a non-Latin filename where each character encodes to multiple UTF-8 bytes, the .mood filename length blows up. For example, a CJK character usually encodes to 3 bytes, each then %-encoded, resulting in each input character taking up 9 characters in the output.

Once this gets too long, the filesystem may reject it:

``` pytb
Exception in thread SpectrumMoodbarGenerator:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/exaile/plugins/moodbar/generator.py", line 94, in generate
    callback(uri, data)
  File "/exaile/plugins/moodbar/__init__.py", line 135, in callback
    cache.put(uri, data)
  File "/exaile/plugins/moodbar/cache.py", line 64, in put
    with open(self._get_cache_path(uri), 'wb') as f:
IOError: [Errno 36] File name too long: '[redacted].mood'
```

**Comment by genodeftest** [comment]
Do we have to %-encode URIs at all? Gio/GLib supports UTF-8 encoded URIs. Is this an issue with python?

I'm working on a solution using hashes instead of URIs.
