### ISSUE TITLE
Exaile can not start after updating Manjaro today

### ISSUE THREAD

**Issue by slmeyer** [exaile/exaile#301]
Error is like:
```
Traceback (most recent call last):
  File "/usr/lib/exaile/exaile.py", line 85, in <module>
    main()
  File "/usr/lib/exaile/exaile.py", line 82, in main
    exaile = main.Exaile()
  File "/usr/lib/exaile/xl/main.py", line 155, in __init__
    exit = xldbus.check_exit(self.options, self.args)
  File "/usr/lib/exaile/xl/xldbus.py", line 69, in check_exit
    bus = dbus.SessionBus()
  File "/usr/lib/python2.7/site-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-qB7SRx4eLI: Connection refused
```

**Comment by virtuald** [comment]
That sounds like a dbus problem, have you rebooted?

**Comment by slmeyer** [comment]
Oh - I needed to update configuration files:
/etc/pam.d/systemd-user
/etc/systemd/logind.conf
Then it works again - thanks for a great music player
