### ISSUE TITLE
Make sure Windows installer stuff works

### ISSUE THREAD

**Issue by dangmai** [exaile/exaile#329]
Use PyInstaller to bundle Python, MSYS2 Gstreamer + Gtk3 and other dependencies for Exaile 4

**Comment by virtuald** [comment]
Progress made on this:

* Need to make some fixes to pyinstaller to work in an msys2 environment
* In particular, pywin32 isn't installable, so we used [pywin32-ctypes](https://github.com/enthought/pywin32-ctypes/issues/45) -- but it needs some additions for pyinstaller to be happy. I expect we'll need to fork that, as the upstream seems unresponsive and hasn't had new releases in 3 years.
* Ran into issues with gir files not being present, and so pyinstaller didn't put in the correct typelibs. Need to detect this and fix pyinstaller to fail when this happens
* Still need to update our SDK with changes that quodlibet made

**Comment by virtuald** [comment]
Also, I think given https://github.com/enthought/pywin32-ctypes/issues/16, we'll need to make a fork, as they seem opposed to completely replacing pywin32 (which is needed for pyinstaller to work correctly).

**Comment by dangmai** [comment]
Here's a task list for this issue:

- [ ] PyInstaller and MSYS2 issue: I opened a PR for PyInstaller, and it got approved, still waiting for it be merged: https://github.com/pyinstaller/pyinstaller/pull/2571
- [x] pywin32-ctypes is now forked and lives in own organization: https://github.com/exaile/pywin32-ctypes/tree/pyinstaller
- [x] gir issues have been resolved in PyInstaller on `master`
- [ ] Work on SDK is in early stage. I'll open a PR once it is done

At this point, we can build Exaile 4 with MSYS2, so it's just a matter of automating it w/ the SDK and testing it in an empty Windows environment.

**Comment by genodeftest** [comment]
The windows installer works fine, thank you!
Can this issue be closed?

**Comment by dangmai** [comment]
For sure :) I'm still keeping a look out for issues w.r.t to the installer in case something needs to be fixed, but I agree that this issue can be closed now.

**Comment by genodeftest** [comment]
The windows installer works fine, thank you!

Sadly, it misses a DLL for loading SVG files through GdkPixBuf:
```
18:51:04 WARNING : Failed to add icon name "exaile" from file "C:\PROGRA~2\Exaile\data\images\scalable\exaile.svg": Bildlader-Modul konnte nicht geladen werden: C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll: 'C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll': Das angegebene Modul wurde nicht gefunden. (xlgui.icons)
18:51:04 WARNING : Failed to add icon name "exaile-pause" from file "C:\PROGRA~2\Exaile\data\images\scalable\exaile-pause.svg": Bildlader-Modul konnte nicht geladen werden: C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll: 'C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll': Das angegebene Modul wurde nicht gefunden. (xlgui.icons)
18:51:04 WARNING : Failed to add icon name "exaile-play" from file "C:\PROGRA~2\Exaile\data\images\scalable\exaile-play.svg": Bildlader-Modul konnte nicht geladen werden: C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll: 'C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll': Das angegebene Modul wurde nicht gefunden. (xlgui.icons)
18:51:04 WARNING : Failed to add icon name "office-calendar" from file "C:\PROGRA~2\Exaile\data\images\scalable\office-calendar.svg": Bildlader-Modul konnte nicht geladen werden: C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll: 'C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll': Das angegebene Modul wurde nicht gefunden. (xlgui.icons)
18:51:04 WARNING : Failed to add icon name "extension" from file "C:\PROGRA~2\Exaile\data\images\scalable\extension.svg": Bildlader-Modul konnte nicht geladen werden: C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll: 'C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll': Das angegebene Modul wurde nicht gefunden. (xlgui.icons)
18:51:04 WARNING : Failed to add icon name "artist" from file "C:\PROGRA~2\Exaile\data\images\scalable\artist.svg": Bildlader-Modul konnte nicht geladen werden: C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll: 'C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll': Das angegebene Modul wurde nicht gefunden. (xlgui.icons)
18:51:04 WARNING : Failed to add icon name "genre" from file "C:\PROGRA~2\Exaile\data\images\scalable\genre.svg": Bildlader-Modul konnte nicht geladen werden: C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll: 'C:\Program Files (x86)\Exaile\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll': Das angegebene Modul wurde nicht gefunden. (xlgui.icons)
```

Also, not all required python modules are installed. It looks like this affects only modules which are required by a plugin, but not by core exaile code (`xl` and `xlgui`):

```
19:01:00 ERROR   : Unable to enable plugin lyricsviewer (xl.plugins)
Traceback (most recent call last):
  File "C:/msys32/home/IEUser/exaile/tools/installer/_inst/usr/lib/exaile/xl/plugins.py", line 148, in enable_plugin
  File "C:/msys32/home/IEUser/exaile/tools/installer/_inst/usr/lib/exaile/xl/plugins.py", line 87, in load_plugin
  File "C:\PROGRA~2\Exaile\plugins\lyricsviewer\__init__.py", line 42, in <module>
    from xl import lyrics as xl_lyrics
ImportError: cannot import name lyrics
19:01:10 ERROR   : Unable to enable plugin icecast (xl.plugins)
Traceback (most recent call last):
  File "C:/msys32/home/IEUser/exaile/tools/installer/_inst/usr/lib/exaile/xl/plugins.py", line 148, in enable_plugin
  File "C:/msys32/home/IEUser/exaile/tools/installer/_inst/usr/lib/exaile/xl/plugins.py", line 87, in load_plugin
  File "C:\PROGRA~2\Exaile\plugins\icecast\__init__.py", line 14, in <module>
    from xml.dom import minidom
ImportError: No module named dom
19:01:22 ERROR   : LIBRIVOX: connection error (librivoxsearch)
19:01:28 ERROR   : LIBRIVOX: connection error (librivoxsearch)
19:01:29 ERROR   : LIBRIVOX: connection error (librivoxsearch)
19:01:32 ERROR   : Unable to enable plugin podcasts (xl.plugins)
Traceback (most recent call last):
  File "C:/msys32/home/IEUser/exaile/tools/installer/_inst/usr/lib/exaile/xl/plugins.py", line 148, in enable_plugin
  File "C:/msys32/home/IEUser/exaile/tools/installer/_inst/usr/lib/exaile/xl/plugins.py", line 87, in load_plugin
  File "C:\PROGRA~2\Exaile\plugins\podcasts\__init__.py", line 16, in <module>
    import feedparser
ImportError: No module named feedparser
19:01:38 ERROR   : Unable to enable plugin podcasts (xl.plugins)
```

**Comment by genodeftest** [comment]
Oops, I was too fast with the good news…

**Comment by virtuald** [comment]
I have a friend who used the Windows installer for -beta3, so this is finished.
