### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#37]
Steps to reproduce:
1. Create a new playlist
2. set shuffle mode to "shuffle tracks"
 EDIT: set "repeat all"
3. Add one single song to the playlist
4. Press play
5. Press next
~~~
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/path/to/exaile/xlgui/main.py", line 291, in <lambda>
    lambda *e: player.QUEUE.next(),
  File "/path/to/exaile/xl/player/queue.py", line 169, in next
    track = self.current_playlist.next()
  File "/path/to/exaile/xl/playlist.py", line 1171, in next
    self.__get_next(self.current_position)
  File "/path/to/exaile/xl/playlist.py", line 1142, in __get_next
    return self.__get_next(-1)
  File "/path/to/exaile/xl/playlist.py", line 1142, in __get_next
    return self.__get_next(-1)
~~~
… (the last two lines got repeated >100 times)
~~~
  File "/path/to/exaile/xl/playlist.py", line 1142, in __get_next
    return self.__get_next(-1)
  File "/path/to/exaile/xl/playlist.py", line 1128, in __get_next
    next_index, next = self.__next_random_track(current_position, shuffle_mode)
  File "/path/to/exaile/xl/playlist.py", line 1097, in __next_random_track
    hist = set([ i for i, tr in self.get_shuffle_history() ])
  File "/path/to/exaile/xl/playlist.py", line 1040, in get_shuffle_history
    return  [ (i, self.__tracks[i]) for i in range(len(self)) if \
  File "/path/to/exaile/xl/playlist.py", line 1498, in __len__
    return len(self.__tracks)
RuntimeError: maximum recursion depth exceeded
~~~

**Comment by virtuald** [comment]
@genodeftest I am not able to reproduce this error on Linux

**Comment by genodeftest** [comment]
Did you exactly follow the steps described above? I am using exaile 3.4.3 and I still can reproduce this bug. See https://bugzilla.redhat.com/show_bug.cgi?id=1202560 for details (might or might not help you).

**Comment by sjohannes** [comment]
I can confirm this, but only when Repeat All is also set. Playback continues and nothing seems to really break.

**Comment by genodeftest** [comment]
@sjohannes you are right, I forgot to mention that. I changed the issue description.
