### ISSUE TITLE
lyricsviewer: Pango-related error on startup

### ISSUE THREAD

**Issue by aurabindo** [exaile/exaile#375]
I'm on Archlinux. I see this error in the terminal when I launch exaile from command line.

### Steps to Reproduce (for bugs)
1. cloned commit 1f78c8e4406a9901303d85cacc2dde25eb080932
2. Launch exaile (/.exaile)

### Current Behavior

```
INFO    : Loading Exaile 4.0.0beta1+1f78c8e...
INFO    : Using Python 2.7.13
INFO    : Using PyGObject 3.24.1
INFO    : Loading settings...
INFO    : Using Locale en_US UTF-8

** (exaile.py:4403): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-5f6LCriDEA: Connection refused
INFO    : Using Mutagen 1.37
INFO    : Using GStreamer 1.12.0
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.22.15
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
ERROR   : Event callback exception caught!
Traceback (most recent call last):
  File "/run/media/aj/Buffer/git-clones/exaile/xl/event.py", line 351, in _emit
    event.data, *cb.args, **cb.kwargs)
  File "/run/media/aj/Buffer/git-clones/exaile/xl/plugins.py", line 117, in __on_new_plugin_loaded
    fn()
  File "/run/media/aj/Buffer/git-clones/exaile/plugins/lyricsviewer/__init__.py", line 72, in on_gui_loaded
    self.__lyricsviewer = LyricsViewer(self.__exaile)
  File "/run/media/aj/Buffer/git-clones/exaile/plugins/lyricsviewer/__init__.py", line 115, in __init__
    self.__initialize_widgets()
  File "/run/media/aj/Buffer/git-clones/exaile/plugins/lyricsviewer/__init__.py", line 141, in __initialize_widgets
    self.__on_option_set(None, xl_settings, 'plugin/lyricsviewer/lyrics_font')
  File "/run/media/aj/Buffer/git-clones/exaile/plugins/lyricsviewer/__init__.py", line 146, in __on_option_set
    css_from_pango = guiutil.css_from_pango_font_description(pango_font_str)
  File "/run/media/aj/Buffer/git-clones/exaile/xlgui/guiutil.py", line 645, in css_from_pango_font_description
    new_font = Pango.FontDescription.from_string(pango_font_str)
TypeError: Argument 0 does not allow None as a value
```
Exaile does not crash, just that its an ugly error.

**Comment by sjohannes** [comment]
Thanks. I think it's just missing the code to handle the case when the font preference doesn't exist.
