### ISSUE TITLE
Fix long annoing udisks exception

### ISSUE THREAD

**Issue by mexicarne** [exaile/exaile#400]
Hello, 

this patch fix exceptions on the systems, where Udisks is not available (like FreeBSD):

```
ERROR   : Failed to connect to udisks2, autodetection of devices will be disabled.
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/hal.py", line 144, in connect
    self.obj = self._connect()
  File "/usr/local/lib/exaile/xl/hal.py", line 366, in _connect
    obj = self.get_object_by_path('/org/freedesktop/UDisks2')
  File "/usr/local/lib/exaile/xl/hal.py", line 176, in get_object_by_path
    return UDisksDBusWrapper(self.bus, self.root, path, iface_type)
  File "/usr/local/lib/exaile/xl/hal.py", line 78, in __init__
    self.obj = bus.get_object(root, path)
  File "/usr/local/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/local/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/local/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/local/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/local/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks2 was not provided by any .service files
ERROR   : Failed to connect to udisks, autodetection of devices will be disabled.
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/hal.py", line 144, in connect
    self.obj = self._connect()
  File "/usr/local/lib/exaile/xl/hal.py", line 404, in _connect
    obj = self.get_object_by_path('/org/freedesktop/UDisks')
  File "/usr/local/lib/exaile/xl/hal.py", line 176, in get_object_by_path
    return UDisksDBusWrapper(self.bus, self.root, path, iface_type)
  File "/usr/local/lib/exaile/xl/hal.py", line 78, in __init__
    self.obj = bus.get_object(root, path)
  File "/usr/local/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/local/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/local/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/local/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/local/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files
```

[fix-udisks-exc.txt](https://github.com/exaile/exaile/files/1065909/fix-udisks-exc.txt)

**Comment by genodeftest** [comment]
As I don't have a system without UDisks at hand, does this bug also freeze Exaile? If yes, then there's a bigger issue here…

**Comment by mexicarne** [comment]
No, it does not. It just a cosmetic defect that was over there since Exaile 3.x or earlier. It doesn't affect any actual functionality that is not related to movable media.

**Comment by genodeftest** [comment]
Actually, the code (try/except block around xl/hal:144) catches the exception. It should not print a stacktrace though. This is not a bug, just an inconvenient log level. Will commit a fix soon.

**Comment by mexicarne** [comment]
Thank you! This works fine here.
```
INFO    : Loading devices...
INFO    : Failed to connect to udisks2, autodetection of devices will be disabled.
INFO    : Failed to connect to udisks, autodetection of devices will be disabled.
INFO    : Loading interface...
```
