### ISSUE TITLE
Headless mode: Exaile crashes on startup with segmentation faults

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#409]
### Steps to Reproduce (for bugs)
1. start exaile by running `python ./exaile.py`, without specifying the `--startgui` parameter. You might want to add the `--debug` flag.

### Expected Behavior
start

### Current Behavior
crash with segmentation fault (SIGSEGV):
```
#0  0x00007ffff6cbb64b in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6cbd450 in __GI_abort () at abort.c:89
#2  0x00007fffecb4cc60 in g_slice_free1 (mem_size=mem_size@entry=24, mem_block=mem_block@entry=0x555555f384c0) at gslice.c:1109
#3  0x00007fffecb2b0c9 in g_list_delete_link (list=<optimized out>, link_=link_@entry=0x555555f384c0 = {...}) at glist.c:612
#4  0x00007fffe52d52e9 in process_on_globals_closures (display_wayland=0x555555f2c080 [GdkWaylandDisplay]) at gdkdisplay-wayland.c:191
#5  0x00007fffe52d52e9 in gdk_registry_handle_global (data=0x555555f2c080, registry=<optimized out>, id=<optimized out>, interface=<optimized out>, version=<optimized out>) at gdkdisplay-wayland.c:456
#6  0x00007fffefac0bde in ffi_call_unix64 () at ../src/x86/unix64.S:76
#7  0x00007fffefac054f in ffi_call (cif=cif@entry=0x7fffffffaa70, fn=<optimized out>, rvalue=<optimized out>, rvalue@entry=0x0, avalue=avalue@entry=0x7fffffffab40) at ../src/x86/ffi64.c:525
#8  0x00007fffdf1a3dd4 in wl_closure_invoke (closure=closure@entry=0x555555f3dd00, flags=flags@entry=1, target=<optimized out>, target@entry=0x555555f35250, opcode=opcode@entry=0, data=<optimized out>)
    at src/connection.c:935
#9  0x00007fffdf1a0998 in dispatch_event (display=display@entry=0x555555f27020, queue=<optimized out>)
    at src/wayland-client.c:1310
#10 0x00007fffdf1a1c54 in dispatch_queue (queue=0x555555f270e8, display=0x555555f27020)
    at src/wayland-client.c:1456
```

Python traceback:
```
Traceback (most recent call first):
  File "/usr/lib64/python2.7/site-packages/gi/overrides/GLib.py", line 599, in iteration
    return super(MainContext, self).iteration(may_block)
  File "/home/christian/src/EXAILE/exaile-2/xl/main.py", line 610, in __mainloop
    context.iteration(True)
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 777, in __bootstrap
    self.__bootstrap_inner()
```

### Possible Solution
In headless mode, `xl.main.Exaile.mainloop_init()` starts the main loop on a separate thread. This might break. I thought the `GLib.MainLoop` must be started on the main thread or at least on the same thread as other Gtk code ran. As a result, the main loop should be run on the main thread. This is just a guess.
Another option would be preventing any Gtk+ code being run on the main thread before, but that will be rather tricky. I don't really have a clue what is going on.

### Environment
* Operating System and version: Fedora 26 with glib2-2.52.3-1.fc26.x86_64, gtk3-3.22.16-1.fc26.x86_64, python2-2.7.13-11.fc26.x86_64, gstreamer1-1.12.1-1.fc26.x86_64
* Exaile Version: Exaile 4.0.0 beta 2

**Comment by genodeftest** [comment]
When I disable all plugins, it works fine and exits.

Maybe we should disable all plugins in headless mode? What is this headless mode even there for?

**Comment by virtuald** [comment]
I'm fine with getting rid of headless mode, I can't imagine many people would use it. I've never used it.

I agree that starting the mainloop on a separate thread probably won't work in more recent versions of Gtk/GLib.
