### ISSUE TITLE
Error loading SmartPlaylist while scanning collection

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#456]
### Steps to Reproduce (for bugs)

1. Start from empty collection
2. Add collection, scan it
3. Try to load Smart Playlist

### Current Behavior
```
ERROR   : Error loading smart playlist
Traceback (most recent call last):
  File "exaile/xlgui/panel/playlists.py", line 213, in open_item
    item = item.get_playlist(self.collection)
  File "exaile/xl/playlist.py", line 1825, in get_playlist
    search_string, matchers = self._create_search_data(collection)
  File "exaile/xl/playlist.py", line 1882, in _create_search_data
    raise ValueError("Loading %s: %s" % (self.name, str(e)))
ValueError: Loading PLAYLISTNAME: dictionary changed size during iteration
```

**Comment by virtuald** [comment]
This is going to require a lot of work, and it isn't encountered frequently, so pushing it to post-4.0
