### ISSUE TITLE
Traceback when resorting a playlist

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#462]
When sorting a playlist very fast, I'm getting a traceback.

### Steps to Reproduce (for bugs)
1. Have a "large" playlist, large enough that it takes more than a few 100 milliseconds to sort it.
2. Double-click on any column
3. Watch console output

### Expected Behavior
No traceback

### Current Behavior
I'm getting this error:
```
ERROR   : Event callback exception caught!
Traceback (most recent call last):
  File "/path/to/exaile/xl/event.py", line 350, in _emit
    event.data, *cb.args, **cb.kwargs)
  File "/path/to/exaile/xlgui/widgets/playlist.py", line 1443, in on_tracks_removed
    self.remove(self.iter_nth_child(None, position))
TypeError: Argument 1 does not allow None as a value
```
Sometimes, that's also
```
ERROR   : Event callback exception caught!
Traceback (most recent call last):
  File "/path/to/exaile/xl/event.py", line 350, in _emit
    event.data, *cb.args, **cb.kwargs)
  File "/path/to/exaile/xlgui/widgets/playlist.py", line 1438, in on_tracks_added
    self._load_data(tracks)
  File "/path/to/exaile/xlgui/widgets/playlist.py", line 1506, in _load_data
    self.data_load_queue.extend(tracks)
AttributeError: 'NoneType' object has no attribute 'extend'
```

### Possible solution:
I have no clue why "on_tracks_removed" is even called.

### Environment
* Operating System and version: Fedora 26, python2-2.7.14-2.fc26.x86_64
* Exaile Version: latest git master (af00c467561394aa373c0accff6f7e6267d0dcc3)

**Comment by virtuald** [comment]
Thanks!
