### ISSUE TITLE
Seekbar invisible

### ISSUE THREAD

**Issue by aurabindo** [exaile/exaile#508]
### Steps to Reproduce (for bugs)

1. Compile from github, and install
2. Play some files

### Expected Behavior

While the audio plays, the seekbar (timeline) should be visible

### Current Behavior

Timeline is invisible. When I click where its supposed to contain the seekbar, it seeks (below the play/pause buttons)

![exaile](https://user-images.githubusercontent.com/1412512/40544843-34cfb456-6047-11e8-9cd2-3902975aec47.png)

### Environment

* Operating System and version: Ubuntu 18.04

* Exaile Version: 46912890ceac1c6ac8052f614aea5ca73f73b338

**Comment by sjohannes** [comment]
Huh, I've never seen anything like this. Could you run Exaile from a terminal, and copy anything that you think might be relevant (warnings, tracebacks etc.)?

**Comment by aurabindo** [comment]
```
INFO    : Loading Exaile 4.0.0beta3...
INFO    : Using Python 2.7.15rc1
INFO    : Using PyGObject 3.26.1
INFO    : Loading settings...
INFO    : Using Locale en_IN ISO8859-1
INFO    : Using Mutagen 1.38
INFO    : Using GStreamer 1.14.0
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.22.30
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
WARNING : Failed to get pixbuf from "image-x-generic": Icon 'image-x-generic' not present in theme ubuntu-mono-dark
WARNING : Failed to get pixbuf from "audio-x-generic": Icon 'audio-x-generic' not present in theme ubuntu-mono-dark
WARNING : Failed to get pixbuf from "audio-x-generic": Icon 'audio-x-generic' not present in theme ubuntu-mono-dark
WARNING : Failed to get pixbuf from "audio-x-generic": Icon 'audio-x-generic' not present in theme ubuntu-mono-dark
WARNING : Failed to get pixbuf from "folder": Icon 'folder' not present in theme ubuntu-mono-dark
WARNING : Failed to get pixbuf from "view-refresh": Icon 'view-refresh' not present in theme ubuntu-mono-dark
WARNING : Failed to get pixbuf from "audio-x-generic": Icon 'audio-x-generic' not present in theme ubuntu-mono-dark
WARNING : Failed to get pixbuf from "folder": Icon 'folder' not present in theme ubuntu-mono-dark
WARNING : Failed to get pixbuf from "folder": Icon 'folder' not present in theme ubuntu-mono-dark
WARNING : Failed to get pixbuf from "audio-x-generic": Icon 'audio-x-generic' not present in theme ubuntu-mono-dark
INFO    : Connecting panel events...
INFO    : Done loading main window...
ERROR   : Event callback exception caught!
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/event.py", line 354, in _emit
    event.data, *cb.args, **cb.kwargs)
  File "/usr/local/lib/exaile/xl/plugins.py", line 117, in __on_new_plugin_loaded
    fn()
  File "/usr/local/share/exaile/plugins/equalizer/__init__.py", line 324, in on_gui_loaded
    self.window = EqualizerWindow()
  File "/usr/local/share/exaile/plugins/equalizer/__init__.py", line 161, in __init__
    self.load_presets()
  File "/usr/local/share/exaile/plugins/equalizer/__init__.py", line 263, in load_presets
    preset.append(float(vals[i]))
ValueError: could not convert string to float: 
ERROR   : Unhandled exception while walking on <__gi__.GLocalFile object at 0x7fe2ec0faf00 (GLocalFile at 0x55cfe5a2b900)>.
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/common.py", line 561, in walk
    Gio.FileQueryInfoFlags.NONE, None):
Error: g-io-error-quark: Error opening directory '/media/aj/Buffer/Entertainment/Music/malayalam': No such file or directory (1)
ERROR   : Unhandled exception while walking on <__gi__.GLocalFile object at 0x7fe2ec0faeb0 (GLocalFile at 0x55cfe5a2b980)>.
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/common.py", line 561, in walk
    Gio.FileQueryInfoFlags.NONE, None):
Error: g-io-error-quark: Error opening directory '/media/aj/Buffer/Entertainment/Music/unclassified': No such file or directory (1)
ERROR   : Unhandled exception while walking on <__gi__.GLocalFile object at 0x7fe2ec0faeb0 (GLocalFile at 0x55cfe5a2bfa0)>.
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/common.py", line 561, in walk
    Gio.FileQueryInfoFlags.NONE, None):
Error: g-io-error-quark: Error opening directory '/media/aj/Buffer/Entertainment/Music/telungu': No such file or directory (1)
ERROR   : Unhandled exception while walking on <__gi__.GLocalFile object at 0x7fe2ec0faeb0 (GLocalFile at 0x55cfe5a2c240)>.
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/common.py", line 561, in walk
    Gio.FileQueryInfoFlags.NONE, None):
Error: g-io-error-quark: Error opening directory '/media/aj/Buffer/Entertainment/Music/kannada': No such file or directory (1)
ERROR   : Unhandled exception while walking on <__gi__.GLocalFile object at 0x7fe2ec0faeb0 (GLocalFile at 0x55cfe5a2bf80)>.
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/common.py", line 561, in walk
    Gio.FileQueryInfoFlags.NONE, None):
Error: g-io-error-quark: Error opening directory '/media/aj/Buffer/Entertainment/Music/english': No such file or directory (1)
ERROR   : Unhandled exception while walking on <__gi__.GLocalFile object at 0x7fe2ec0faeb0 (GLocalFile at 0x55cfe5a2c260)>.
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/common.py", line 561, in walk
    Gio.FileQueryInfoFlags.NONE, None):
Error: g-io-error-quark: Error opening directory '/media/aj/Buffer/Entertainment/Music/hindi': No such file or directory (1)
ERROR   : Unhandled exception while walking on <__gi__.GLocalFile object at 0x7fe2ec0faeb0 (GLocalFile at 0x55cfe5a2c1a0)>.
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/common.py", line 561, in walk
    Gio.FileQueryInfoFlags.NONE, None):
Error: g-io-error-quark: Error opening directory '/media/aj/Buffer/Entertainment/Music/unsynced': No such file or directory (1)
ERROR   : Unhandled exception while walking on <__gi__.GLocalFile object at 0x7fe2ec0faeb0 (GLocalFile at 0x55cfe5a2c200)>.
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/common.py", line 561, in walk
    Gio.FileQueryInfoFlags.NONE, None):
Error: g-io-error-quark: Error opening directory '/media/aj/Buffer/Entertainment/Music/tamil': No such file or directory (1)
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xlgui/widgets/playback.py", line 434, in do_draw
    Gtk.ProgressBar.do_draw(self, context)
KeyError: 'could not find foreign type Context'
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xlgui/widgets/playback.py", line 434, in do_draw
    Gtk.ProgressBar.do_draw(self, context)
KeyError: 'could not find foreign type Context'
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xlgui/widgets/playback.py", line 434, in do_draw
    Gtk.ProgressBar.do_draw(self, context)
KeyError: 'could not find foreign type Context'
INFO    : Exaile is shutting down...
INFO    : Tearing down plugins...
INFO    : Saving state...
INFO    : Bye!
```

**Comment by genodeftest** [comment]
Ok, the relevant part is this traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xlgui/widgets/playback.py", line 434, in do_draw
    Gtk.ProgressBar.do_draw(self, context)
KeyError: 'could not find foreign type Context'
```
It looks like your computer is missing GObject Introspection libraries or its dependencies for cairo. I don't know how the Ubuntu/Debian package is called, but it should provide these two files:
* `cairo-1.0.typelib`
* `cairo-1.0.gir`
You may want to try installing these packages: `cairo-gobject libgirepository gobject-introspection gir1.2-glib-2.0 gir1.2-freedesktop`. The names may differ a bit as I only have debian package names at hand. Please report back wether that solved your issue.

**Comment by rokm** [comment]
On Ubuntu 18.04, the package in question seems to be called ```python-gi-cairo```.

**Comment by aurabindo** [comment]
Thank you so much @genodeftest @rokm ! Installing the package fixed the issue for me!
