### ISSUE TITLE
Deploy to many GNU/Linux distributions using Snapcraft

### ISSUE THREAD

**Issue by reitzig** [exaile/exaile#514]
Exaile is not in the Ubuntu 18.04 repositories. Compiling from source is not really a consumer-friendly deployment method.

Snapcraft seems to be a reasonable approach to deploy applications to a wide range of GNU/Linux distributions.

**Comment by virtuald** [comment]
If you're using linux, I still tend to assume that you're at least vaguely technical. I know this isn't always true, but in general it's a good bet.

The primary reason we're no longer in Ubuntu was because we (I) were silly and delayed the 4.0 release striving for perfection instead of 'good enough' (and 3.x was removed because of gst 0.10). I expect that once we have a 4.0 final release that we would eventually make our way back in (though, that's not guaranteed).

If you're willing to set up snapcraft and set up a way to make it auto-package and auto-upload using Travis-CI, I'm happy to provide some minimal assistance in doing that -- but I'm not willing to personally put a large amount of effort into that (but perhaps someone else is).

**Comment by reitzig** [comment]
> If a user is using linux, I still tend to assume that they're at least vaguely technical. I know this isn't always true, but in general it's a good bet.

Ubuntu is clearly targetting "normals", among others. That said, `aptitude`/`apt-get`, `snap` etc. on the CLI _are_ probably as tech-savvy as it gets, often. Searching AskUbuntu for the packages I need to install for `make` to work (very non-informative error) is definitely nothing I'd expect even motivated half-techies to do.

> I expect that once we have a 4.0 final release that we would eventually make our way back in

We can hope. I take it you don't know the maintainer of that package?

> If you're willing to set up snapcraft and set up a way to make it auto-package and auto-upload using Travis-CI

Haha, I was afraid you'd say that. But I wanted to check out Snapcraft, anyway, so I just might. Don't hold your breath, though.

**Comment by dangmai** [comment]
@virtuald I already have Exaile build for my Arch installation (not the one on AUR) so I know what to expect for Exaile packaging. I can take on this (setting up Travis/build the Snap) if you think that's worthwhile (i.e. you're willing to maintain it as part of this repository after it's set up, since I'd rather not maintain it myself).

**Comment by javiercantero** [comment]
Note that if exaie were an official Debian package (like the 3.x branch was) then it will be picked for any Debian derivative including Ubuntu and Linux Mint.

**Comment by Ezwen** [comment]
A flatpak for Exaile deployed on flathub could be nice as well! But it does require some packaging work.

**Comment by virtuald** [comment]
Flatpak is another thing I'm not opposed to if someone else does the work and makes it automated, but I don't want to do the work.

**Comment by jeteokeeffe** [comment]
I'd like to help out with creating a flatpak but have a question. Berkeley DB seems to be depreciated in Python 3 (https://docs.python.org/2/library/bsddb.html). I notice 4.1.0 rc is using all python 3, not longer requires Python 2 at all. So, how is bsddb supposed to work? Does bsddb actually work with Python 3? Also, do you know where I can find the proper version of bsddb and download, I'll need headers and lib ( if I actually do need to include it)?

I'm testing my flatpak and it definitely requires it
sh-5.0$ python3 exaile.py 
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "exaile.py", line 64, in <module>
    main()
  File "exaile.py", line 60, in main
    exaile = main.Exaile()
  File "/app/lib/exaile/xl/main.py", line 457, in __init__
    _do_heavy_imports()
  File "/app/lib/exaile/xl/main.py", line 59, in _do_heavy_imports
    from xl import common, xdg
  File "/app/lib/exaile/xl/common.py", line 47, in <module>
    import bsddb3 as bsddb
ModuleNotFoundError: No module named 'bsddb3'

https://github.com/jeteokeeffe/exaile-flathub

**Comment by rokm** [comment]
Take a look at https://pypi.org/project/bsddb3/

**Comment by sjohannes** [comment]
Regarding compiling the Berkeley DB library itself, you may want to check how Linux distributions do it (e.g. [Arch Linux](https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/db)). Practically all of them use an old version (5.3.x) because the licence is more convenient.

**Comment by jeteokeeffe** [comment]
I'm close but bsddb3 isn't finding the includes/lib I've manually built with berkeley db. Flatpak builder builds everything in /run/build/<module> and installs it in /app/include and /app/lib/. I believe the setup.py in bsddb3 has libs hardcoded in 4 directories and /app isn't one of them. So, I think I need to add a patch to setup.py. If anybody wants a look (https://github.com/jeteokeeffe/exaile-flathub)

```
{
  "app-id": "org.exaile.exaile",
  "runtime": "org.gnome.Platform",
  "runtime-version": "3.34",
  "sdk": "org.gnome.Sdk",
  "command": "exaile",
    "finish-args": [
    "--share=ipc",
    "--socket=x11",
    "--socket=wayland",
    "--socket=fallback-x11",
    "--socket=session-bus",
    "--share=network",
    "--filesystem=home"
  ],
  "modules": [
    {
      "name": "cpython",
      "sources": [
        {
          "type": "archive",
          "url": "https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz",
          "md5": "f9f3768f757e34b342dbc06b41cbc844"
        }
      ]
    },
    {
      "name": "berkeleydb",
      "buildsystem": "simple",
      "build-commands": [
        "cd build_unix && ../dist/configure --prefix=/app --enable-compat185 --enable-dbm --enable-shared",
        "cd build_unix && make",
        "cd build_unix && make install"
      ],
      "sources": [
        {
          "type": "archive",
          "url": "http://anduin.linuxfromscratch.org/BLFS/bdb/db-5.3.28.tar.gz",
          "sha256": "e0a992d740709892e81f9d93f06daf305cf73fb81b545afe72478043172c3628"
        }
      ]
    },
    "python-depends.json",
    {
      "name": "exaile",
      "buildsystem": "simple",
      "build-commands": [
        "make",
        "make install PREFIX=/app"
      ],
      "sources": [
        {
          "type": "git",
          "url": "https://github.com/exaile/exaile.git",
          "tag": "4.1.0-alpha1"
        },
        {
          "type": "file",
          "path": "Makefile.changes"
        },
        {
          "type": "patch",
          "path": "Makefile.patch"
        }
      ]
    }
  ]
}
```

Output from the build
```
flatpak-builder -v --install-deps-from=flathub --force-clean flatpak-build org.exaile.exaile.json

Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-9588952p
Created temporary directory: /tmp/pip-req-tracker-giaqb1ua
Created requirements tracker '/tmp/pip-req-tracker-giaqb1ua'
Created temporary directory: /tmp/pip-install-fmue1w8g
Looking in links: file:///run/build/python3-bsddb3
Collecting bsddb3
  0 location(s) to search for versions of bsddb3:
  Skipping link: not a file: file:///run/build/python3-bsddb3 (from -f)
  Found link file:///run/build/python3-bsddb3/bsddb3-6.2.7.tar.gz, version: 6.2.7
  Local files found: /run/build/python3-bsddb3/bsddb3-6.2.7.tar.gz
  Given no hashes to check 1 links for project 'bsddb3': discarding no candidates
  Using version 6.2.7 (newest of versions: 6.2.7)
  Added bsddb3 from file:///run/build/python3-bsddb3/bsddb3-6.2.7.tar.gz to build tracker '/tmp/pip-req-tracker-giaqb1ua'
    Running setup.py (path:/tmp/pip-install-fmue1w8g/bsddb3/setup.py) egg_info for package bsddb3
    Running command python setup.py egg_info
    Can't find a local Berkeley DB installation.
    (suggestion: try the --berkeley-db=/path/to/bsddb option)
Cleaning up...
```

**Comment by jeteokeeffe** [comment]
https://github.com/exaile/exaile/pull/697

Complete and added a link on how to submit your app to flathub. Let me know if you have questions or need help.

**Comment by genodeftest** [comment]
Affecting both flatpak and snapcraft: Every single time any dependency gets an update, we need to update the package. I personally don't like this as it generates work. Can we have this fully automated? Or do we have someone to step up as a package maintainer to release a new package about once a week or at most once a month? If not, I'd vote against having this kind of package distribution, as it will only keep pushing bugs to users which have long been fixed.

**Comment by sjohannes** [comment]
It's probably okay if we can treat it similarly to the Windows installer. That is: if we know of a serious issue regarding one of the dependencies, we'll release a new version, but otherwise we leave it alone forever. I'm willing to maintain it at that level, but I don't know what expectations Flathub puts on maintainers.

**Comment by jeteokeeffe** [comment]
@genodeftest Yeah, a change in the dependency does require a change in the build. This could be fixed by using the old school requirements.txt file that specifically sets the version. I think the best option is moving to meson for builds, it would definitely simply the build.

**Comment by Mailaender** [comment]
I submitted https://github.com/flathub/flathub/pull/3731.

**Comment by Mailaender** [comment]
Note that there is https://github.com/flathub/flatpak-external-data-checker to automate updates. However, for Berkeley DB I had to use older versions due to license conflicts.
