### ISSUE TITLE
Mutagen error prevents track metadata changes

### ISSUE THREAD

**Issue by Carmina16** [exaile/exaile#535]
### Steps to Reproduce (for bugs)
1. Edit properties of a read-only MP3 file.
2. Click **Apply**

### Expected Behavior
An exception should appear, but the track properties saved.

### Current Behavior
An exception should appear, and the track metadata updated.

### Environment
* Operating System and version: Linux x86_64
* Exaile Version:  4.0.0 rc1

**Comment by virtuald** [comment]
What do you mean the track properties saved?

**Comment by Carmina16** [comment]
Stored in the database.

**Comment by genodeftest** [comment]
For future reference:

    WARNING : Error saving track
    Traceback (most recent call last):
      File "/path/to/exaile/xlgui/properties.py", line 215, in _tags_write
        self._write_tag(track, tag, trackdata[tag])
      File "/path/to/exaile/xlgui/properties.py", line 198, in _write_tag
        track.set_tag_disk(tag, value)
      File "/path/to/exaile/xl/trax/track.py", line 846, in set_tag_disk
        f.write_tags({tag: values})
      File "/path/to/exaile/xl/metadata/_base.py", line 297, in write_tags
        self.save()
      File "/path/to/exaile/xl/metadata/_base.py", line 136, in save
        self.mutagen.save()
      File "/usr/lib/python2.7/site-packages/mutagen/_util.py", line 139, in wrapper
        writable, create) as h:
      File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/usr/lib/python2.7/site-packages/mutagen/_util.py", line 256, in _openfile
        raise MutagenError(e)
    MutagenError: [Errno 13] Permission denied: u'<filename>'
