### ISSUE TITLE
Corrupted equalizer presets prevent plugin usage

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#550]
Received from a user:

### Environment

* Operating System and version: Windows

* Exaile Version:  4.0.0rc1

```
02:36:25 ERROR   : Unable to enable plugin equalizer (xl.plugins)
Traceback (most recent call last):
  File "C:/msys32/home/IEUser/exaile/tools/installer/_inst/usr/lib/exaile/xl/plugins.py", line 153, in enable_plugin
  File "C:/msys32/home/IEUser/exaile/tools/installer/_inst/usr/lib/exaile/xl/plugins.py", line 123, in __enable_new_plugin
  File "C:\PROGRA~2\Exaile\plugins\equalizer\__init__.py", line 349, in on_gui_loaded
    self.window = EqualizerWindow()
  File "C:\PROGRA~2\Exaile\plugins\equalizer\__init__.py", line 183, in __init__
    self.load_presets()
  File "C:\PROGRA~2\Exaile\plugins\equalizer\__init__.py", line 285, in load_presets
    preset.append(float(vals[i]))
ValueError: could not convert string to float:
```

I haven't looked yet, but I'm betting that either

* The eq-presets.dat isn't being bundled correctly with the installer
* Or the plugin isn't looking in the right place for it

**Comment by virtuald** [comment]
It seems the equalizer presets aren't being serialized properly at all, so if a user tries to save a preset then it breaks the equalizer and it no longer works. I don't have time to dig in to it at the moment.

A workaround for users that run into this is delete the eq_presets.dat file in the config directory... since it doesn't contain anything anyways.
