### ISSUE TITLE
Error when starting Exaile

### ISSUE THREAD

**Issue by dickmaat** [exaile/exaile#60]
I'm using exaile version 3.4.3 on fedora 21.
When I start exaile I get this error:
```
Traceback (most recent call last):
  File "/usr/share/exaile/exaile.py", line 85, in <module>
    main()
  File "/usr/share/exaile/exaile.py", line 82, in main
    exaile = main.Exaile()
  File "/usr/share/exaile/xl/main.py", line 164, in __init__
    from xl.version import __version__
  File "/usr/share/exaile/xl/version.py", line 49, in <module>
    revision = get_current_revision(xdg.exaile_dir)
  File "/usr/share/exaile/xl/version.py", line 43, in get_current_revision
    'git', 'rev-parse', '--short=7', 'HEAD'
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
However If i add the option 'shell=True' and change line /usr/share/exaile/xl/version.py (42) 
from: 
```
        return subprocess.check_output([
            'git', 'rev-parse', '--short=7', 'HEAD'
        ]).strip()
```
to:
```
        return subprocess.check_output([
            'git', 'rev-parse', '--short=7', 'HEAD'
        ], shell=True).strip()
```
exaile starts normally.

**Comment by virtuald** [comment]
Thanks for the bug report. Will make sure it gets fixed in the next release (which will be this weekend I think). The better fix I think is to add OSError to the list of exceptions that get caught there.

**Comment by dickmaat** [comment]
As I'm learning python I decided to attempt to fix the bug myself following your suggestion of adding the OSError exception. So I removed the "Shell=True" option and added the OSError exception. So line 45 becomes:     except (subprocess.CalledProcessError , OSError):
instead of:     except subprocess.CalledProcessError:
The modification worked: exaile (still) starts!

**Comment by virtuald** [comment]
Great to hear.
