### ISSUE TITLE
exaile fails to run with gstreamer 1.16

### ISSUE THREAD

**Issue by mexicarne** [exaile/exaile#689]
exaile start failing after gstreamer 1.16 update. The culprit is:
```python
        self.playbin = Gst.ElementFactory.make("playbin", "%s-playbin" % self.name)
        if self.playbin is None:
            raise TypeError("gstreamer 1.x base plugins not installed!")
```
in File "/usr/local/lib/exaile/xl/player/gst/engine.py", line 369, in __init__

Running this sample in standalone session saying this:
```python
>>> import gi
>>> gi.require_version('Gst', '1.0')
>>> from gi.repository import Gst
>>> playbin = Gst.ElementFactory.make("playbin", "test-playbin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gi/overrides/Gst.py", line 246, in make
    return Gst.ElementFactory.make(factory_name, instance_name)
TypeError: unbound method fake_method() must be called with ElementFactory instance as first argument (got str instance instead)
```
it looks like playbin api had changed.

my environment:
freebsd 13, python 2.7.17, gstreamer 1.16.1, exaile 4.0.2

original traceback
```python
ERROR   : Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/main.py", line 575, in __init__
    self.__init()
  File "/usr/local/lib/exaile/xl/main.py", line 643, in __init
    from xlgui.widgets.info import Splash
  File "/usr/local/lib/exaile/xlgui/__init__.py", line 40, in <module>
    from xl import common, player, providers, settings, version, xdg
  File "/usr/local/lib/exaile/xl/player/__init__.py", line 40, in <module>
    PLAYER = player.ExailePlayer('player')
  File "/usr/local/lib/exaile/xl/player/player.py", line 80, in __init__
    self._setup_engine(disable_autoswitch)
  File "/usr/local/lib/exaile/xl/player/player.py", line 100, in _setup_engine
    self._engine.initialize()
  File "/usr/local/lib/exaile/xl/player/gst/engine.py", line 153, in initialize
    self.main_stream = AudioStream(self)
  File "/usr/local/lib/exaile/xl/player/gst/engine.py", line 369, in __init__
    raise TypeError("gstreamer 1.x base plugins not installed!")
TypeError: gstreamer 1.x base plugins not installed!
```

**Comment by mexicarne** [comment]
ok, I actually forgot the Gst.Init method, but anyway:
```python
>>> from gi.repository import Gst
>>> Gst.init(None)
[]
>>> playbin = Gst.ElementFactory.make("playbin", "test-playbin")
>>> type(playbin)
<type 'NoneType'>
```

**Comment by sjohannes** [comment]
There's likely a different issue here; this works for me on GStreamer 1.16.2.

The error message indicates that you may be missing some GStreamer plugins. [Try checking](https://www.freebsd.org/cgi/ports.cgi?query=gstreamer1&stype=all&sektion=all) if there is something that you may need to install (maybe `gstreamer1-plugins`?).

You can also try playing some file with `gst-play-1.0` and see if it works.

**Comment by mexicarne** [comment]
Hmm, looks like you are right. Playing the file with gst-play-1.0 yields "Failed to create 'playbin' element. Check your GStreamer installation.". I have all the plugins installed and gst-inspect-1.0 show them, but there are no playbin plugin in the list. I'll check with OS vendor. Thank you.

**Comment by mexicarne** [comment]
It was a problem with my gstreamer installation
