### ISSUE TITLE
Crashes instantly on KDE Neon

### ISSUE THREAD

**Issue by Herpderpus666** [exaile/exaile#690]
On my system (KDE Neon, Plasma 5.18) exailed (installed with make, make install) crashes instantly when launching.

This is what gets displayed when launching from terminal:

```
INFO    : Loading Exaile 4.0.2...
INFO    : Using Python 2.7.17
INFO    : Using PyGObject 3.26.1
INFO    : Loading settings...
INFO    : Using Locale en_US UTF-8
INFO    : Using Mutagen 1.38
INFO    : Using GStreamer 1.14.5
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.22.30
INFO    : Using GTK+ theme Breeze
WARNING : Failed to get pixbuf from "starred": Icon 'starred' not present in theme breeze-dark
ERROR   : Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/main.py", line 575, in __init__
    self.__init()
  File "/usr/local/lib/exaile/xl/main.py", line 643, in __init
    from xlgui.widgets.info import Splash
  File "/usr/local/lib/exaile/xlgui/widgets/info.py", line 36, in <module>
    from xlgui.widgets import playlist
  File "/usr/local/lib/exaile/xlgui/widgets/playlist.py", line 41, in <module>
    from xlgui.widgets.common import AutoScrollTreeView
  File "/usr/local/lib/exaile/xlgui/widgets/common.py", line 42, in <module>
    from xlgui import icons
  File "/usr/local/lib/exaile/xlgui/icons.py", line 757, in <module>
    MANAGER = IconManager()
  File "/usr/local/lib/exaile/xlgui/icons.py", line 536, in __init__
    self.pixbuf_from_icon_name('starred', size=Gtk.IconSize.MENU)
  File "/usr/local/lib/exaile/xlgui/icons.py", line 61, in __init__
    pixbuf.get_colorspace(),
AttributeError: 'NoneType' object has no attribute 'get_colorspace'
```

I think it's unable to find some icon and this unhandled exceptions the program. It doesn't matter which icon theme I select, breeze dark or whatever else, error is always the same except for the theme name.

### Environment

OS: KDE neon 5.18
Kernel: x86_64 Linux 5.3.0-28-generic
Resolution: 1920x1080
DE: KDE 5.67.0 / Plasma 5.18.0
WM: KWin
GTK Theme: Breeze [GTK2/3]
Icon Theme: breeze-dark

**Comment by sjohannes** [comment]
Fixed in master and backported to the 4.0.x branch. Feel free to reopen if it still doesn't work.
