### ISSUE TITLE
ManagerDialog: too many values to unpack

### ISSUE THREAD

**Issue by mexicarne** [exaile/exaile#699]
Hello. Got this harmless (not actually crashing exaile runtime) exception by simply opening Tools -> Device Manager window in menu.

```python
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xlgui/menu.py", line 354, in <lambda>
    lambda *x: get_main().controller.show_devices(),
  File "/usr/local/lib/exaile/xlgui/__init__.py", line 225, in show_devices
    from xlgui.devices import ManagerDialog
  File "/usr/local/lib/exaile/xlgui/devices.py", line 38, in <module>
    class ManagerDialog(Gtk.Window):
  File "/usr/local/lib/exaile/xlgui/devices.py", line 45, in ManagerDialog
    tree_devices, model = GtkTemplate.Child.widgets(5)
ValueError: too many values to unpack (expected 2)
```

It's on FreeBSD with Exaile 4.1.0-alpha1.

```
INFO    : Loading Exaile devel...
INFO    : Using Python 3.7.7
INFO    : Using PyGObject 3.28.3
INFO    : Loading settings...
INFO    : Using Locale en_US UTF-8
INFO    : Using Mutagen 1.42.0
INFO    : Using GStreamer 1.16.2
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.24.10
INFO    : Using GTK+ theme Adwaita-dark
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xlgui/menu.py", line 354, in <lambda>
    lambda *x: get_main().controller.show_devices(),
  File "/usr/local/lib/exaile/xlgui/__init__.py", line 225, in show_devices
    from xlgui.devices import ManagerDialog
  File "/usr/local/lib/exaile/xlgui/devices.py", line 38, in <module>
    class ManagerDialog(Gtk.Window):
  File "/usr/local/lib/exaile/xlgui/devices.py", line 45, in ManagerDialog
    tree_devices, model = GtkTemplate.Child.widgets(5)
ValueError: too many values to unpack (expected 2)
INFO    : Exaile is shutting down...
INFO    : Tearing down plugins...
INFO    : Saving state...
INFO    : Bye!
```

**Comment by mexicarne** [comment]
FreeBSD port of exaile depends on bsdisks [1] (it's an Udisks2 implementation for BSD systems), so it looks like they may be incompatible in some aspects. Anyway, if I just remove the bsdisks to let exaile ignore it altogether, then runtime fails with:

```python
INFO    : Connected to udisks2
ERROR   : Introspect error on :1.342:/org/freedesktop/UDisks2: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.403" (uid=1999 pid=89459 comm="python3.7: exaile ") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.342" (uid=0 pid=66096 comm="/usr/local/bin/bsdisks --no-debug ")
ERROR   : Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xl/main.py", line 561, in __init__
    self.__init()
  File "/usr/local/lib/exaile/xl/main.py", line 728, in __init
    if udisks2.connect():
  File "/usr/local/lib/exaile/xl/hal.py", line 160, in connect
    self._add_all(self.obj)
  File "/usr/local/lib/exaile/xl/hal.py", line 399, in _add_all
    for path in obj.GetManagedObjects():
  File "/usr/local/lib/python3.7/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/local/lib/python3.7/site-packages/dbus/proxies.py", line 147, in __call__
    **keywords)
  File "/usr/local/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.403" (uid=1999 pid=89459 comm="python3.7: exaile ") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination=":1.342" (uid=0 pid=66096 comm="/usr/local/bin/bsdisks --no-debug ")
```

So does UDisks2 is an uncoditional requirement of new Exaile?

[1] https://bitbucket.org/arrowd/bsdisks

**Comment by sjohannes** [comment]
Thanks for the report. I'll push a fix once GitHub comes back alive.

> So does UDisks2 is an uncoditional requirement of new Exaile?

It can be disabled by passing `--no-hal` on the command line. Currently the only thing it's used for is CD autodetection.

**Comment by mexicarne** [comment]
Thank you. That works.
