### ISSUE TITLE
Icecast: IncompleteRead error while reading genres list

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#912]
### Steps to Reproduce

Enable Icecast plugin.

### Expected Behavior

Genres are read and populated to the Radio panel.

### Current Behavior

Error in console:
```pytb
Exception in thread Thread-5 (_load_station):
Traceback (most recent call last):
  File "C:\msys\mingw64\lib\python3.11\http\client.py", line 599, in _read_chunked
    value.append(self._safe_read(chunk_left))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\msys\mingw64\lib\python3.11\http\client.py", line 640, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 3096 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\msys\mingw64\lib\python3.11\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\msys\mingw64\lib\python3.11\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\exaile\xlgui\panel\radio.py", line 529, in _load_station
    lists = driver.get_lists(no_cache=no_cache)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\exaile\plugins\icecast\__init__.py", line 136, in get_lists
    genre_list = self._get_genres()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\exaile\plugins\icecast\__init__.py", line 354, in _get_genres
    body = response.read()
           ^^^^^^^^^^^^^^^
  File "C:\msys\mingw64\lib\python3.11\http\client.py", line 467, in read
    return self._read_chunked(amt)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\msys\mingw64\lib\python3.11\http\client.py", line 605, in _read_chunked
    raise IncompleteRead(b''.join(value)) from exc
http.client.IncompleteRead: IncompleteRead(77728 bytes read)
```

### Discussion

This is probably a server issue, but opening the URL <https://dir.xiph.org/genres> in a web browser works fine.

### Environment

* Operating System and version: Windows, with up-to-date MSYS (Python 3.11.7)
* Exaile Version: 96a16537

**Comment by rokm** [comment]
This seems to be reproducible with following stand-alone code in up-to-date MSYS as well as on my Fedora 39 with python 3.12:
```python
import http.client
import urllib.parse

genres_url = 'https://dir.xiph.org/genres'
user_agent = 'Exaile/4.1.3 IcecastRadio/4.1.3 (+https://www.exaile.org)'

hostinfo = urllib.parse.urlparse(genres_url)

c = http.client.HTTPConnection(hostinfo.netloc, timeout=20)
c.request('GET', hostinfo.path)
response = c.getresponse()

if response.status != 200:
    raise Exception('Error connecting to Icecast server.')

try:
    body = response.read()
    print(body)
    print("COMPLETE!")
except http.client.IncompleteRead as e:
    body = e.partial
    print(body)
    print("PARTIAL!")
``` 

Unless we want to handle partial reads ourselves, perhaps we should switch to higher-level library that does that, for example `requests`?

```python
import requests

user_agent = 'Exaile/4.1.3 IcecastRadio/4.1.3 (+https://www.exaile.org)'

res = requests.get('https://dir.xiph.org/genres', headers={'User-Agent': user_agent})
data = res.text

print(data)
```

**Comment by luzip665** [comment]
@rokm 
Your code works here
Ubuntu 22.04 with Python 3.10.12 and 3.11.0rc1 
Debian Testing with Python 3.11.7

**Comment by rokm** [comment]
Hmm, it seems to work now for me as well. So it might indeed be an intermittent server issue.

**Comment by sjohannes** [comment]
Yeah, it's working again now; I think it's fine to close this for now unless it reappears. Thanks for testing!
