### ISSUE TITLE
Queue page breaks when all tracks is removed

### ISSUE THREAD

**Issue by Aric-prog** [exaile/exaile#919]
### Steps to Reproduce (for bugs)

1. Add a song to the queue
2. Remove songs until queue is empty

### Expected Behavior

Queue should still be usable after removing all songs.

### Current Behavior

Adding songs to the queue will show it visually, but song cannot be removed/played. The tab will also show "Queue(0)" even if songs are added.

```
INFO    : PyGObject works
INFO    : GTK+ works
INFO    : GStreamer works
INFO    : Mutagen works
04:34:17,968:INFO    : Loading Exaile 4.1.3+24916a6... (xl.main)
04:34:17,977:INFO    : Using Python 3.11.8 (xl.version)
04:34:17,977:INFO    : Using PyGObject 3.46.0 (xl.version)
04:34:17,977:INFO    : Loading settings... (xl.main)
04:34:17,983:DEBUG   : Settings loaded from C:\Users\username\AppData\Local/exaile (xl.main)
04:34:17,984:INFO    : Using Locale English_Indonesia 1252 (xl.version)
04:34:17,994:INFO    : Using Mutagen 1.47.0 (xl.version)
04:34:18,020:DEBUG   : No support for Mod metadata because libmodplug could not be found. (xl.metadata.mod)
04:34:18,048:DEBUG   : Provider m3u registered for service playlist-format-converter with target None (xl.providers)
04:34:18,049:DEBUG   : Provider pls registered for service playlist-format-converter with target None (xl.providers)
04:34:18,050:DEBUG   : Provider asx registered for service playlist-format-converter with target None (xl.providers)
04:34:18,051:DEBUG   : Provider xspf registered for service playlist-format-converter with target None (xl.providers)
04:34:18,106:INFO    : Using GStreamer 1.24.1 (xl.version)
04:34:18,126:DEBUG   : Set user volume: 0.09 (xl.player.gst.engine [player-a1])
04:34:18,127:INFO    : Reconfiguring crossfading (xl.player.gst.engine [player])
04:34:18,127:INFO    : Crossfade: disabled (xl.player.gst.engine [player])
04:34:18,147:INFO    : Using GTK+ 3.24.41 (xl.version)
04:34:18,218:INFO    : Using GTK+ theme Adwaita (xl.version)
04:34:18,223:DEBUG   : Provider tracknumber registered for service tag-formatting with target None (xl.providers)
04:34:18,224:DEBUG   : Provider discnumber registered for service tag-formatting with target None (xl.providers)
04:34:18,226:DEBUG   : Provider artist registered for service tag-formatting with target None (xl.providers)
04:34:18,226:DEBUG   : Provider __length registered for service tag-formatting with target None (xl.providers)
04:34:18,227:DEBUG   : Provider __startoffset registered for service tag-formatting with target None (xl.providers)
04:34:18,227:DEBUG   : Provider __stopoffset registered for service tag-formatting with target None (xl.providers)
04:34:18,227:DEBUG   : Provider __rating registered for service tag-formatting with target None (xl.providers)
04:34:18,228:DEBUG   : Provider year registered for service tag-formatting with target None (xl.providers)
04:34:18,228:DEBUG   : Provider __last_played registered for service tag-formatting with target None (xl.providers)
04:34:18,228:DEBUG   : Provider __date_added registered for service tag-formatting with target None (xl.providers)
04:34:18,229:DEBUG   : Provider __loc registered for service tag-formatting with target None (xl.providers)
04:34:18,229:DEBUG   : Provider comment registered for service tag-formatting with target None (xl.providers)
04:34:18,234:DEBUG   : Provider tags registered for service covers with target None (xl.providers)
04:34:18,235:DEBUG   : Provider localfile registered for service covers with target None (xl.providers)
04:34:18,462:DEBUG   : Provider tracknumber registered for service playlist-columns with target None (xl.providers)
04:34:18,463:DEBUG   : Provider title registered for service playlist-columns with target None (xl.providers)
04:34:18,464:DEBUG   : Provider artist registered for service playlist-columns with target None (xl.providers)
04:34:18,464:DEBUG   : Provider albumartist registered for service playlist-columns with target None (xl.providers)
04:34:18,465:DEBUG   : Provider composer registered for service playlist-columns with target None (xl.providers)
04:34:18,466:DEBUG   : Provider album registered for service playlist-columns with target None (xl.providers)
04:34:18,466:DEBUG   : Provider __length registered for service playlist-columns with target None (xl.providers)
04:34:18,467:DEBUG   : Provider discnumber registered for service playlist-columns with target None (xl.providers)
04:34:18,467:DEBUG   : Provider __rating registered for service playlist-columns with target None (xl.providers)
04:34:18,468:DEBUG   : Provider date registered for service playlist-columns with target None (xl.providers)
04:34:18,468:DEBUG   : Provider year registered for service playlist-columns with target None (xl.providers)
04:34:18,469:DEBUG   : Provider genre registered for service playlist-columns with target None (xl.providers)
04:34:18,470:DEBUG   : Provider __bitrate registered for service playlist-columns with target None (xl.providers)
04:34:18,470:DEBUG   : Provider __loc registered for service playlist-columns with target None (xl.providers)
04:34:18,471:DEBUG   : Provider __basename registered for service playlist-columns with target None (xl.providers)
04:34:18,471:DEBUG   : Provider __playcount registered for service playlist-columns with target None (xl.providers)
04:34:18,472:DEBUG   : Provider bpm registered for service playlist-columns with target None (xl.providers)
04:34:18,473:DEBUG   : Provider language registered for service playlist-columns with target None (xl.providers)
04:34:18,473:DEBUG   : Provider __last_played registered for service playlist-columns with target None (xl.providers)
04:34:18,474:DEBUG   : Provider __date_added registered for service playlist-columns with target None (xl.providers)
04:34:18,475:DEBUG   : Provider schedule_time registered for service playlist-columns with target None (xl.providers)
04:34:18,475:DEBUG   : Provider comment registered for service playlist-columns with target None (xl.providers)
04:34:18,476:DEBUG   : Provider grouping registered for service playlist-columns with target None (xl.providers)
04:34:18,476:DEBUG   : Provider __startoffset registered for service playlist-columns with target None (xl.providers)
04:34:18,477:DEBUG   : Provider __stopoffset registered for service playlist-columns with target None (xl.providers)
04:34:18,477:DEBUG   : Provider website registered for service playlist-columns with target None (xl.providers)
04:34:18,478:DEBUG   : Provider album registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,479:DEBUG   : Provider albumartist registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,479:DEBUG   : Provider artist registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,479:DEBUG   : Provider bpm registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,480:DEBUG   : Provider __bitrate registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,480:DEBUG   : Provider comment registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,480:DEBUG   : Provider composer registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,481:DEBUG   : Provider date registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,481:DEBUG   : Provider __date_added registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,481:DEBUG   : Provider discnumber registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,482:DEBUG   : Provider __basename registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,482:DEBUG   : Provider genre registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,482:DEBUG   : Provider grouping registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,483:DEBUG   : Provider language registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,483:DEBUG   : Provider __last_played registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,483:DEBUG   : Provider __length registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,484:DEBUG   : Provider __loc registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,484:DEBUG   : Provider __playcount registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,485:DEBUG   : Provider __rating registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,485:DEBUG   : Provider schedule_time registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,486:DEBUG   : Provider __startoffset registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,486:DEBUG   : Provider __stopoffset registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,486:DEBUG   : Provider title registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,487:DEBUG   : Provider tracknumber registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,487:DEBUG   : Provider website registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,487:DEBUG   : Provider year registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,488:DEBUG   : Provider columns_separator registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,488:DEBUG   : Provider resizable registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,488:DEBUG   : Provider autosize registered for service playlist-columns-menu with target None (xl.providers)
04:34:18,490:DEBUG   : Provider new-tab registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,491:DEBUG   : Provider new-tab-sep registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,491:DEBUG   : Provider save registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,491:DEBUG   : Provider saveas registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,492:DEBUG   : Provider rename registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,492:DEBUG   : Provider clear registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,492:DEBUG   : Provider tab-close-sep registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,493:DEBUG   : Provider export registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,493:DEBUG   : Provider export-files registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,493:DEBUG   : Provider tab-export-sep registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,494:DEBUG   : Provider tab-close registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:18,504:DEBUG   : Provider enqueue registered for service playlist-context-menu with target None (xl.providers)
04:34:18,505:DEBUG   : Provider toggle-spat registered for service playlist-context-menu with target None (xl.providers)
04:34:18,505:DEBUG   : Provider rating registered for service playlist-context-menu with target None (xl.providers)
04:34:18,506:DEBUG   : Provider sep1 registered for service playlist-context-menu with target None (xl.providers)
04:34:18,506:DEBUG   : Provider remove registered for service playlist-context-menu with target None (xl.providers)
04:34:18,507:DEBUG   : Provider randomize registered for service playlist-context-menu with target None (xl.providers)
04:34:18,507:DEBUG   : Provider playlist-menu registered for service playlist-context-menu with target None (xl.providers)
04:34:18,507:DEBUG   : Provider sep2 registered for service playlist-context-menu with target None (xl.providers)
04:34:18,508:DEBUG   : Provider properties registered for service playlist-context-menu with target None (xl.providers)
04:34:18,520:DEBUG   : Provider new-marker registered for service progressbar-context-menu with target None (xl.providers)
04:34:18,521:DEBUG   : Provider jumpto-marker registered for service playback-marker-context-menu with target None (xl.providers)
04:34:18,521:DEBUG   : Provider move-marker registered for service playback-marker-context-menu with target None (xl.providers)
04:34:18,522:DEBUG   : Provider remove-marker registered for service playback-marker-context-menu with target None (xl.providers)
04:34:18,950:INFO    : Loading plugins... (xl.main)
04:34:18,960:DEBUG   : Provider playback-playpause registered for service tray-icon-context with target None (xl.providers)
04:34:18,961:DEBUG   : Provider playback-next registered for service tray-icon-context with target None (xl.providers)
04:34:18,961:DEBUG   : Provider playback-prev registered for service tray-icon-context with target None (xl.providers)
04:34:18,962:DEBUG   : Provider playback-stop registered for service tray-icon-context with target None (xl.providers)
04:34:18,962:DEBUG   : Provider playback-sep registered for service tray-icon-context with target None (xl.providers)
04:34:18,962:DEBUG   : Provider playlist-mode-shuffle registered for service tray-icon-context with target None (xl.providers)
04:34:18,963:DEBUG   : Provider playlist-mode-repeat registered for service tray-icon-context with target None (xl.providers)
04:34:18,963:DEBUG   : Provider playlist-mode-dynamic registered for service tray-icon-context with target None (xl.providers)
04:34:18,963:DEBUG   : Provider playlist-mode-sep registered for service tray-icon-context with target None (xl.providers)
04:34:18,964:DEBUG   : Provider rating registered for service tray-icon-context with target None (xl.providers)
04:34:18,964:DEBUG   : Provider remove-current registered for service tray-icon-context with target None (xl.providers)
04:34:18,965:DEBUG   : Provider misc-actions-sep registered for service tray-icon-context with target None (xl.providers)
04:34:18,965:DEBUG   : Provider quit-application registered for service tray-icon-context with target None (xl.providers)
04:34:18,984:DEBUG   : Provider new-playlist registered for service playlist-notebook-actions with target None (xl.providers)
04:34:19,010:DEBUG   : Loaded plugin grouptagger (xl.plugins)
04:34:19,020:DEBUG   : Loaded plugin icecast (xl.plugins)
04:34:19,137:DEBUG   : Loaded plugin mpris2 (xl.plugins)
04:34:19,140:DEBUG   : Provider rgvolume registered for service gst_audio_filter with target None (xl.providers)
04:34:19,144:DEBUG   : rgvolume: Removing all elements (xl.player.gst.gst_utils)
04:34:19,144:DEBUG   : rgvolume: Adding audioconvert0 (xl.player.gst.gst_utils)
04:34:19,145:DEBUG   : rgvolume: Adding rgvolume0 (xl.player.gst.gst_utils)
04:34:19,145:DEBUG   : Provider rglimiter registered for service gst_audio_filter with target None (xl.providers)
04:34:19,146:DEBUG   : rgvolume: Removing all elements (xl.player.gst.gst_utils)
04:34:19,146:DEBUG   : rgvolume: Adding audioconvert1 (xl.player.gst.gst_utils)
04:34:19,147:DEBUG   : rgvolume: Adding rgvolume1 (xl.player.gst.gst_utils)
04:34:19,148:DEBUG   : rglimiter: Removing all elements (xl.player.gst.gst_utils)
04:34:19,148:DEBUG   : rglimiter: Adding rglimiter0 (xl.player.gst.gst_utils)
04:34:19,148:DEBUG   : rglimiter: Adding audioconvert2 (xl.player.gst.gst_utils)
04:34:19,149:DEBUG   : Loaded plugin replaygain (xl.plugins)
04:34:19,154:DEBUG   : Provider enqueue registered for service track-panel-menu with target None (xl.providers)
04:34:19,154:DEBUG   : Provider append registered for service track-panel-menu with target None (xl.providers)
04:34:19,155:DEBUG   : Provider replace registered for service track-panel-menu with target None (xl.providers)
04:34:19,155:DEBUG   : Provider rating registered for service track-panel-menu with target None (xl.providers)
04:34:19,156:DEBUG   : Provider tp-sep registered for service track-panel-menu with target None (xl.providers)
04:34:19,156:DEBUG   : Provider properties registered for service track-panel-menu with target None (xl.providers)
04:34:19,157:DEBUG   : Provider cp-sep registered for service collection-panel-context-menu with target None (xl.providers)
04:34:19,157:DEBUG   : Provider open-directory registered for service collection-panel-context-menu with target None (xl.providers)
04:34:19,158:DEBUG   : Provider trash-tracks registered for service collection-panel-context-menu with target None (xl.providers)
04:34:19,159:DEBUG   : Provider fp-sep registered for service files-panel-context-menu with target None (xl.providers)
04:34:19,159:DEBUG   : Provider open-directory registered for service files-panel-context-menu with target None (xl.providers)
04:34:19,159:DEBUG   : Provider trash-tracks registered for service files-panel-context-menu with target None (xl.providers)
04:34:19,160:DEBUG   : Provider new-playlist registered for service playlist-panel-menu with target None (xl.providers)
04:34:19,161:DEBUG   : Provider new-smart-playlist registered for service playlist-panel-menu with target None (xl.providers)
04:34:19,161:DEBUG   : Provider import-playlist registered for service playlist-panel-menu with target None (xl.providers)
04:34:19,161:DEBUG   : Provider top-sep registered for service playlist-panel-menu with target None (xl.providers)
04:34:19,163:DEBUG   : Provider pp-top-sep registered for service playlist-panel-context-menu with target None (xl.providers)
04:34:19,163:DEBUG   : Provider rename-playlist registered for service playlist-panel-context-menu with target None (xl.providers)
04:34:19,163:DEBUG   : Provider edit-playlist registered for service playlist-panel-context-menu with target None (xl.providers)
04:34:19,164:DEBUG   : Provider export-playlist registered for service playlist-panel-context-menu with target None (xl.providers)
04:34:19,164:DEBUG   : Provider export-files registered for service playlist-panel-context-menu with target None (xl.providers)
04:34:19,165:DEBUG   : Provider pp-sep registered for service playlist-panel-context-menu with target None (xl.providers)
04:34:19,165:DEBUG   : Provider delete-playlist registered for service playlist-panel-context-menu with target None (xl.providers)
04:34:19,166:DEBUG   : Provider new-station registered for service radio-panel-menu with target None (xl.providers)
04:34:19,192:DEBUG   : Loaded plugin somafm (xl.plugins)
04:34:19,197:DEBUG   : Loaded plugin developer (xl.plugins)
04:34:19,198:INFO    : Loading collection... (xl.main)
04:34:19,198:DEBUG   : Loading Collection DB from C:\Users\username\AppData\Local/exaile/music.db. (xl.trax.trackdb)
04:34:19,208:INFO    : Loading devices... (xl.main)
04:34:19,211:INFO    : Loading interface... (xl.main)
04:34:19,215:DEBUG   : Provider __local registered for service lyrics with target None (xl.providers)

(exaile:29756): Pango-WARNING **: 04:34:19.275: couldn't load font "Liberation Sans Not-Rotated 4", falling back to "Sans Not-Rotated 4", expect ugly output.
04:34:19,305:INFO    : Loading main window... (xlgui)
04:34:19,331:DEBUG   : Set user volume: 0.09 (xl.player.gst.engine [player-a1])
04:34:19,371:DEBUG   : Provider clear-sep registered for service playlist-closed-tab-menu with target <playlist_container.PlaylistNotebook object at 0x0a956828 (xlgui+playlist_container+PlaylistNotebook at 0x05e68320)> (xl.providers)
04:34:19,372:DEBUG   : Provider clear-history registered for service playlist-closed-tab-menu with target <playlist_container.PlaylistNotebook object at 0x0a956828 (xlgui+playlist_container+PlaylistNotebook at 0x05e68320)> (xl.providers)
04:34:19,372:DEBUG   : Provider saved_tabs-tab-history registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:19,374:DEBUG   : Provider <Primary><Shift>t registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,375:DEBUG   : Adding playlist 0: order1..Playlist 2 (xlgui.playlist_container)
04:34:19,375:DEBUG   : Tab:1; Tag:; Name:Playlist 2 (xlgui.playlist_container)
04:34:19,413:DEBUG   : Provider clear-sep registered for service playlist-closed-tab-menu with target <playlist_container.PlaylistNotebook object at 0x0bbc7e88 (xlgui+playlist_container+PlaylistNotebook at 0x05f1b118)> (xl.providers)
04:34:19,414:DEBUG   : Provider clear-history registered for service playlist-closed-tab-menu with target <playlist_container.PlaylistNotebook object at 0x0bbc7e88 (xlgui+playlist_container+PlaylistNotebook at 0x05f1b118)> (xl.providers)
04:34:19,414:DEBUG   : Provider saved_tabs2-tab-history registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:19,416:DEBUG   : Provider <Primary><Alt>t registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,424:DEBUG   : Provider move-tab registered for service playlist-tab-context-menu with target None (xl.providers)
04:34:19,425:DEBUG   : Provider move-tab registered for service queue-tab-context with target None (xl.providers)
04:34:19,430:DEBUG   : Provider <Primary>S registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,431:DEBUG   : Provider <Shift><Primary>S registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,432:DEBUG   : Provider <Primary>F registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,432:DEBUG   : Provider <Primary>G registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,433:DEBUG   : Provider <Primary><Alt>l registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,433:DEBUG   : Provider <Primary>P registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,433:DEBUG   : Provider <Primary>Right registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,434:DEBUG   : Provider <Primary>Left registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,434:DEBUG   : Provider <Primary>plus registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,435:DEBUG   : Provider <Primary>equal registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,435:DEBUG   : Provider <Primary>minus registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,436:DEBUG   : Provider <Primary>Page_Up registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,436:DEBUG   : Provider <Primary>Page_Down registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,436:DEBUG   : Provider <Alt>N registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,437:DEBUG   : Provider <Alt>I registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,437:DEBUG   : Provider <Alt>R registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,438:DEBUG   : Provider <Alt>L registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,438:DEBUG   : Provider <Alt>1 registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,439:DEBUG   : Provider <Alt>2 registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,439:DEBUG   : Provider <Alt>3 registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,440:DEBUG   : Provider <Alt>4 registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,440:DEBUG   : Provider <Alt>5 registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,440:DEBUG   : Provider <Alt>6 registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,441:DEBUG   : Provider <Alt>7 registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,441:DEBUG   : Provider <Alt>8 registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,441:DEBUG   : Provider <Alt>9 registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,442:DEBUG   : Provider <Alt>0 registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,442:INFO    : Connecting main window events... (xlgui.main)
04:34:19,444:DEBUG   : Provider new-playlist registered for service menubar-file-menu with target None (xl.providers)
04:34:19,445:DEBUG   : Provider new-sep registered for service menubar-file-menu with target None (xl.providers)
04:34:19,445:DEBUG   : Provider open registered for service menubar-file-menu with target None (xl.providers)
04:34:19,446:DEBUG   : Provider open-uri registered for service menubar-file-menu with target None (xl.providers)
04:34:19,446:DEBUG   : Provider open-dirs registered for service menubar-file-menu with target None (xl.providers)
04:34:19,446:DEBUG   : Provider open-sep registered for service menubar-file-menu with target None (xl.providers)
04:34:19,447:DEBUG   : Provider import-playlist registered for service menubar-file-menu with target None (xl.providers)
04:34:19,447:DEBUG   : Provider export-playlist registered for service menubar-file-menu with target None (xl.providers)
04:34:19,448:DEBUG   : Provider export-sep registered for service menubar-file-menu with target None (xl.providers)
04:34:19,448:DEBUG   : Provider close-tab registered for service menubar-file-menu with target None (xl.providers)
04:34:19,449:DEBUG   : Provider restart-application registered for service menubar-file-menu with target None (xl.providers)
04:34:19,449:DEBUG   : Provider quit-application registered for service menubar-file-menu with target None (xl.providers)
04:34:19,450:DEBUG   : Provider <Primary>t registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,450:DEBUG   : Provider <Primary>o registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,450:DEBUG   : Provider <Primary><Shift>o registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,451:DEBUG   : Provider <Primary>w registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,451:DEBUG   : Provider <Primary>r registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,452:DEBUG   : Provider <Primary>q registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,453:DEBUG   : Provider collection-manager registered for service menubar-edit-menu with target None (xl.providers)
04:34:19,454:DEBUG   : Provider queue registered for service menubar-edit-menu with target None (xl.providers)
04:34:19,454:DEBUG   : Provider cover-manager registered for service menubar-edit-menu with target None (xl.providers)
04:34:19,454:DEBUG   : Provider preferences registered for service menubar-edit-menu with target None (xl.providers)
04:34:19,455:DEBUG   : Provider <Primary>m registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,457:DEBUG   : Provider show-playing-track registered for service menubar-view-menu with target None (xl.providers)
04:34:19,458:DEBUG   : Provider show-playing-track-sep registered for service menubar-view-menu with target None (xl.providers)
04:34:19,458:DEBUG   : Provider playlist-utilities registered for service menubar-view-menu with target None (xl.providers)
04:34:19,459:DEBUG   : Provider columns registered for service menubar-view-menu with target None (xl.providers)
04:34:19,459:DEBUG   : Provider clear-playlist registered for service menubar-view-menu with target None (xl.providers)
04:34:19,460:DEBUG   : Provider <Primary>j registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,460:DEBUG   : Provider <Primary>l registered for service mainwindow-accelerators with target None (xl.providers)
04:34:19,461:DEBUG   : Provider device-manager registered for service menubar-tools-menu with target None (xl.providers)
04:34:19,461:DEBUG   : Provider scan-collection registered for service menubar-tools-menu with target None (xl.providers)
04:34:19,462:DEBUG   : Provider slow-scan-collection registered for service menubar-tools-menu with target None (xl.providers)
04:34:19,463:DEBUG   : Provider guide registered for service menubar-help-menu with target None (xl.providers)
04:34:19,463:DEBUG   : Provider shortcuts registered for service menubar-help-menu with target None (xl.providers)
04:34:19,463:DEBUG   : Provider about-sep1 registered for service menubar-help-menu with target None (xl.providers)
04:34:19,464:DEBUG   : Provider report registered for service menubar-help-menu with target None (xl.providers)
04:34:19,464:DEBUG   : Provider logs registered for service menubar-help-menu with target None (xl.providers)
04:34:19,465:DEBUG   : Provider about-sep2 registered for service menubar-help-menu with target None (xl.providers)
04:34:19,465:DEBUG   : Provider about registered for service menubar-help-menu with target None (xl.providers)
04:34:19,472:INFO    : Loading panels... (xlgui.panels)
04:34:19,489:DEBUG   : Reloading collection tree (xlgui.panel.collection)
04:34:19,491:DEBUG   : Provider collection registered for service main-panel with target None (xl.providers)
04:34:19,497:DEBUG   : Provider radio registered for service main-panel with target None (xl.providers)
04:34:19,502:DEBUG   : Provider playlists registered for service main-panel with target None (xl.providers)
04:34:19,513:DEBUG   : Provider files registered for service main-panel with target None (xl.providers)
04:34:19,535:DEBUG   : Provider lyrics registered for service main-panel with target None (xl.providers)
04:34:19,536:DEBUG   : Provider panel-menu registered for service menubar-view-menu with target None (xl.providers)
04:34:19,538:DEBUG   : Provider collection registered for service panel-tab-context with target None (xl.providers)
04:34:19,539:DEBUG   : Provider radio registered for service panel-tab-context with target None (xl.providers)
04:34:19,541:DEBUG   : Provider playlists registered for service panel-tab-context with target None (xl.providers)
04:34:19,544:DEBUG   : Provider files registered for service panel-tab-context with target None (xl.providers)
04:34:19,546:DEBUG   : Provider lyrics registered for service panel-tab-context with target None (xl.providers)
04:34:19,548:INFO    : Connecting panel events... (xlgui)
04:34:19,549:INFO    : Done loading main window... (xlgui)
04:34:19,662:DEBUG   : Provider grouptagger registered for service main-panel with target None (xl.providers)
04:34:19,664:DEBUG   : Provider grouptagger registered for service panel-tab-context with target None (xl.providers)
04:34:19,670:DEBUG   : Provider grouptagger registered for service menubar-tools-menu with target None (xl.providers)
04:34:19,672:DEBUG   : Provider grouptagger registered for service playlist-context-menu with target None (xl.providers)
04:34:19,674:DEBUG   : Provider developer registered for service menubar-tools-menu with target None (xl.providers)
04:34:19,678:DEBUG   : Exaile/4.1.3 IcecastRadio/4.1.3 (+https://www.exaile.org) (icecast)
04:34:19,679:DEBUG   : Provider icecast registered for service radio with target None (xl.providers)
04:34:19,682:DEBUG   : Exaile/4.1.3 SomaFMRadio/4.1.3 (+https://www.exaile.org) (somafm)
04:34:19,683:DEBUG   : Provider somafm registered for service radio with target None (xl.providers)
04:34:19,687:DEBUG   : Saving Collection DB to C:\Users\username\AppData\Local/exaile/music.db. (xl.trax.trackdb)
04:34:19,694:DEBUG   : File count: 37 (xl.collection)
04:34:19,860:DEBUG   : Reloading collection tree (xlgui.panel.collection)
04:34:20,361:DEBUG   : Saving settings... (xl.settings)

(exaile:29756): Gtk-CRITICAL **: 04:40:13.808: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed
04:40:13,808:ERROR   : Event callback exception caught! (xl.event)
Traceback (most recent call last):
  File "D:/Repositories/exaile/xl/event.py", line 357, in _emit
    fn.__call__(
  File "D:/Repositories/exaile/xlgui/widgets/playlist.py", line 2031, in on_tracks_removed
    self.remove(self.iter_nth_child(None, position))
TypeError: Argument 1 does not allow None as a value

Locals at innermost frame:

{ 'event_type': 'playlist_tracks_removed',
  'playlist': <xl.player.queue.PlayQueue object at 0x05649a70>,
  'position': -1,
  'self': <playlist.PlaylistModel object at 0x0ebd59c8 (xlgui+widgets+playlist+PlaylistModel at 0...
  'track': <Track 'Aria of the Soul' by 'Haruko Komiya' from 'Persona 3 Reload Limited Box Origin...
  'tracks': [ ( -1,
                <Track 'Aria of the Soul' by 'Haruko Komiya' from 'Persona 3 Reload Limited Box O...

04:40:13,811:ERROR   : Unhandled exception (gtk)
Traceback (most recent call last):
  File "D:/Repositories/exaile/xlgui/widgets/playlist.py", line 1688, in on_drag_data_received
    self.playlist.extend(tracks)
  File "D:/Repositories/exaile/xl/playlist.py", line 1672, in extend
    self[len(self) : len(self)] = other
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "D:/Repositories/exaile/xl/player/queue.py", line 311, in __setitem__
    self.play()
  File "D:/Repositories/exaile/xl/player/queue.py", line 257, in play
    self.next()
  File "D:/Repositories/exaile/xl/player/queue.py", line 169, in next
    self.current_position = 0
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:/Repositories/exaile/xl/playlist.py", line 1010, in set_current_position
    raise IndexError("Cannot set position past end of playlist")
IndexError: Cannot set position past end of playlist

Locals at innermost frame:

{ 'oldposition': -1,
  'position': 0,
  'self': <xl.player.queue.PlayQueue object at 0x05649a70>}
```

### Environment

* Operating System and version: Windows 10, ver. 22H2

* Exaile Version: 4.1.3+24916a6
GStreamer: 1.24.1
GTK+: 3.24.41
GTK+ theme: Adwaita
Locale: English_Indonesia 1252
Mutagen: 1.47.0
PyGObject: 3.46.0
Python: 3.11.8

**Comment by luzip665** [comment]
Hi

Do you have "Remove after playback" active?
May be you can post your settings?

I can only reproduce if I remove the current playing song from the queue.

**Comment by Aric-prog** [comment]
Hey,
Not sure if i still have the other settings, but yes i have remove after playback active when i posted this (song gets removed when i fast forward).
