### ISSUE TITLE
Library scan freezes

### ISSUE THREAD

**Issue by flberger** [exaile/exaile#938]
After an update, the Exaile library scan freezes at 23%. It can be canceled in the UI, but then I am left with no library items. A scan restart has no effect at all. 

### Steps to Reproduce (for bugs)
1. Run Exaile from terminal: `LC_ALL="C" exaile --safemode --debug`
2. The library scan starts
3. The library scan freezes at 23%, see image

![2024-exaile-stuck](https://github.com/user-attachments/assets/dd66a889-15e5-41d7-a1a6-895b6ded4420)

### Expected Behavior
The library scan should finish, and the library items should be available for browsing.

### Current Behavior
The library seems to stall at 23 % forever. The output on the command line is:

    Exception in thread Thread-3:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
        self.run()
      File "/usr/lib/exaile/xl/collection.py", line 100, in run
        self.collection.rescan_libraries(
      File "/usr/lib/exaile/xl/collection.py", line 258, in rescan_libraries
        library.rescan(notify_interval=scan_interval, force_update=force_update)
      File "/usr/lib/exaile/xl/collection.py", line 795, in rescan
        tr = self.update_track(fil, force_update=force_update)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/exaile/xl/collection.py", line 730, in update_track
        tr = trax.Track(uri)
             ^^^^^^^^^^^^^^^
      File "/usr/lib/exaile/xl/trax/track.py", line 272, in __init__
        self.read_tags(notify_changed=False)
      File "/usr/lib/exaile/xl/trax/track.py", line 400, in read_tags
        if not self.is_supported():
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/exaile/xl/trax/track.py", line 471, in is_supported
        f = metadata.get_format(loc)
            ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/exaile/xl/metadata/__init__.py", line 150, in get_format
        return formatclass(loc)
               ^^^^^^^^^^^^^^^^
      File "/usr/lib/exaile/xl/metadata/_base.py", line 125, in __init__
        self.load()
      File "/usr/lib/exaile/xl/metadata/wav.py", line 44, in load
        f = wave.open(fp)
            ^^^^^^^^^^^^^
      File "/usr/lib/python3.12/wave.py", line 649, in open
        return Wave_read(f)
               ^^^^^^^^^^^^
      File "/usr/lib/python3.12/wave.py", line 286, in __init__
        self.initfp(f)
      File "/usr/lib/python3.12/wave.py", line 266, in initfp
        self._read_fmt_chunk(chunk)
      File "/usr/lib/python3.12/wave.py", line 383, in _read_fmt_chunk
        raise Error('unknown format: %r' % (wFormatTag,))
    wave.Error: unknown format: 3
    
### Environment

* Operating System and version: Linux 6.11.6-artix1-1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

* Exaile Version:
  - Exaile 4.1.3
  - GStreamer: 1.24.9
  - GTK+: 3.24.43
  - GTK+ theme: Adwaita
  - Mutagen: 1.47.0
  - PyGObject: 3.50.0
  - Python: 3.12.7

**Comment by luzip665** [comment]
Hi.

There's something wrong with the file. See https://docs.python.org/3/library/wave.html#wave.Error

In #939 I added a patch to make the error visible. Can you test?

**Comment by flberger** [comment]
I have tested that version. The scan completes, Exaile no longer freezes, I can see my library and play songs like before.

On the command line output, I now see messages like `INFO    : Unable to read file: <redacted>.wav`

The commit fixes the bug.

**Comment by luzip665** [comment]
Thank you for testing.

Is the wav-File working in an other (not python based) player?
